// SPDX-License-Identifier: Apache-2.0
"use client";

import {
  BoxesIcon,
  BoxIcon,
  FileCheckIcon,
  FileQuestionIcon,
  LayersIcon,
  SearchXIcon,
  ShieldAlertIcon,
  WandSparklesIcon,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { ApplicationKind, ApplicationSource } from "@/lib/api/fleet-schemas";

/** The display name, falling back to the discovered name. */
export const displayName = (a: { display_name: string | null; name: string }): string =>
  a.display_name?.trim() ? a.display_name : a.name;

const amber = "border-amber-500/60 text-amber-700 dark:text-amber-400";

export function KindBadge({ kind }: { kind: ApplicationKind }) {
  switch (kind) {
    case "compose":
      return (
        <Badge variant="secondary">
          <LayersIcon aria-hidden="true" /> Compose
        </Badge>
      );
    case "container":
      return (
        <Badge variant="outline">
          <BoxIcon aria-hidden="true" /> Container
        </Badge>
      );
    case "manual":
      return (
        <Badge variant="outline">
          <BoxesIcon aria-hidden="true" /> Manual
        </Badge>
      );
  }
}

/**
 * Provenance of the Compose definition. "Reconstructed" is deliberately loud
 * (dashed violet border, icon and text): it was generated from runtime
 * metadata and is NOT the operator's original file.
 */
export function SourceBadge({ source }: { source: ApplicationSource }) {
  switch (source) {
    case "original":
      return (
        <Badge variant="outline" className="text-emerald-700 dark:text-emerald-400">
          <FileCheckIcon aria-hidden="true" /> Original
        </Badge>
      );
    case "reconstructed":
      return (
        <Badge
          variant="outline"
          data-source="reconstructed"
          className="border-dashed border-violet-500 bg-violet-500/10 font-semibold tracking-wide text-violet-700 uppercase dark:text-violet-300"
          title="Generated by DBR² from Docker runtime metadata; not the original Compose file"
        >
          <WandSparklesIcon aria-hidden="true" /> Reconstructed
        </Badge>
      );
    default:
      return (
        <Badge variant="outline" className="text-muted-foreground">
          <FileQuestionIcon aria-hidden="true" /> Unknown
        </Badge>
      );
  }
}

/** High-severity unprotected paths; renders nothing for 0. */
export function UnprotectedBadge({ count }: { count: number }) {
  if (count <= 0) return null;
  return (
    <Badge variant="destructive">
      <ShieldAlertIcon aria-hidden="true" /> {count} unprotected
    </Badge>
  );
}

export function MissingBadge({ since }: { since: string }) {
  return (
    <Badge variant="outline" className={amber} title={`Missing from the latest inventory since ${since}`}>
      <SearchXIcon aria-hidden="true" /> Missing
    </Badge>
  );
}

export function SeverityBadge({ severity }: { severity: string }) {
  if (severity === "high") {
    return (
      <Badge variant="destructive">
        <ShieldAlertIcon aria-hidden="true" /> High
      </Badge>
    );
  }
  if (severity === "low") return <Badge variant="outline">Low</Badge>;
  return <Badge variant="outline">{severity}</Badge>;
}

/** Volume class (ADR-0006): Local, External or Ephemeral; Unused when no container mounts it. */
export function VolumeClassBadge({ cls }: { cls: string }) {
  switch (cls) {
    case "local":
      return <Badge variant="secondary">Local</Badge>;
    case "external":
      return (
        <Badge variant="outline" className={amber}>
          External
        </Badge>
      );
    case "ephemeral":
      return (
        <Badge variant="outline" className="text-muted-foreground">
          Ephemeral
        </Badge>
      );
    case "unused":
      return (
        <Badge variant="outline" className="border-dashed text-muted-foreground">
          Unused
        </Badge>
      );
    default:
      return <Badge variant="outline">{cls}</Badge>;
  }
}
