#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Tests for scripts/ci/check-spdx.sh.
set -euo pipefail
# shellcheck source=scripts/ci/test/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

check() { "$CI/check-spdx.sh"; }

new_repo spdx
mkdir -p cmd/x db web/src/app web/scripts web/node_modules/pkg spikes/s internal/store deployments/docker .github/workflows docs
printf '// SPDX-License-Identifier: Apache-2.0\n\npackage main\n' >cmd/x/main.go
printf -- '-- SPDX-License-Identifier: Apache-2.0\nSELECT 1;\n' >db/q.sql
printf '#!/usr/bin/env bash\n# SPDX-License-Identifier: Apache-2.0\n' >run.sh
printf '// SPDX-License-Identifier: Apache-2.0\nexport {}\n' >web/src/app/page.tsx
printf '# SPDX-License-Identifier: Apache-2.0\nFROM scratch\n' >deployments/docker/Dockerfile.services
printf '# SPDX-License-Identifier: Apache-2.0\nname: x\n' >.github/workflows/ci.yml
# Not checked: spikes, node_modules, docs, lockfiles, *.sum, generated code.
printf 'package s\n' >spikes/s/main.go
printf 'module.exports = 1\n' >web/node_modules/pkg/index.js
printf '# no header\n' >docs/readme.md
printf 'x h1:abc\n' >go.sum
printf '{}\n' >web/package-lock.json
printf '// Code generated by sqlc. DO NOT EDIT.\n// versions:\n\npackage store\n' >internal/store/db.go
printf '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage agentpb\n' >internal/store/agent.pb.go
printf 'node_modules/\nignored.go\n' >.gitignore
printf 'package ignored\n' >ignored.go
git add -A
git commit -q -m base

run_case "all headers present passes" 0 check

printf 'package main\n' >cmd/x/other.go
run_case "untracked Go file without header fails" nonzero check
assert "failure names the file" output_contains "cmd/x/other.go"
rm cmd/x/other.go

printf '\n\n\n\n\n// SPDX-License-Identifier: Apache-2.0\npackage main\n' >cmd/x/late.go
run_case "header after line 5 fails" nonzero check
rm cmd/x/late.go

printf 'export const x = 1\n' >web/src/app/util.ts
run_case "web/src TS file without header fails" nonzero check
rm web/src/app/util.ts

printf 'echo hi\n' >web/scripts/gen
run_case "web/scripts file without header fails" nonzero check
rm web/scripts/gen

printf 'FROM scratch\n' >web/Dockerfile
run_case "Dockerfile without header fails" nonzero check
rm web/Dockerfile

printf 'SELECT 1;\n' >db/bad.sql
git add db/bad.sql
git commit -q -m "tracked bad"
run_case "tracked SQL file without header fails" nonzero check
git rm -q db/bad.sql
git commit -q -m "remove"

printf 'package main\n' >cmd/x/gone.go
git add cmd/x/gone.go
rm cmd/x/gone.go
run_case "deleted-but-tracked file is ignored" 0 check

finish
