// SPDX-License-Identifier: Apache-2.0

// DBR² agent protocol (component `agent-protocol`, ADR-0001, ADR-0015).
//
// Phase 1 fixes the session handshake so version compatibility can be
// enforced from the first connection; the command catalogue (snapshot,
// quiesce, restore, …) is added in Phase 2+. Breaking changes require an
// agent-protocol version bump (buf breaking in CI).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectRequest is a message sent by the agent on the session stream.
type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ConnectRequest_Hello
	//	*ConnectRequest_Heartbeat
	Body          isConnectRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetBody() isConnectRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ConnectRequest) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ConnectRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ConnectRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ConnectRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isConnectRequest_Body interface {
	isConnectRequest_Body()
}

type ConnectRequest_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ConnectRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*ConnectRequest_Hello) isConnectRequest_Body() {}

func (*ConnectRequest_Heartbeat) isConnectRequest_Body() {}

// ConnectResponse is a message sent by the gateway on the session stream.
type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ConnectResponse_Welcome
	//	*ConnectResponse_Heartbeat
	Body          isConnectResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetBody() isConnectResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ConnectResponse) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ConnectResponse_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ConnectResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ConnectResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isConnectResponse_Body interface {
	isConnectResponse_Body()
}

type ConnectResponse_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ConnectResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*ConnectResponse_Welcome) isConnectResponse_Body() {}

func (*ConnectResponse_Heartbeat) isConnectResponse_Body() {}

// Hello opens a session and reports versions (ADR-0015: the gateway rejects
// a mismatched agent-protocol MAJOR and flags outdated agents).
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Four-part agent component version, e.g. "0.1.0.57".
	AgentVersion string `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Four-part agent-protocol version the agent speaks, e.g. "0.1.0.0".
	ProtocolVersion string `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Host facts for inventory and compatibility checks.
	Hostname     string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsRelease    string `protobuf:"bytes,4,opt,name=os_release,json=osRelease,proto3" json:"os_release,omitempty"`
	Architecture string `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Commands the agent journaled and is still reporting (ADR-0001 reconnect).
	InflightCommandIds []string `protobuf:"bytes,6,rep,name=inflight_command_ids,json=inflightCommandIds,proto3" json:"inflight_command_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOsRelease() string {
	if x != nil {
		return x.OsRelease
	}
	return ""
}

func (x *Hello) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Hello) GetInflightCommandIds() []string {
	if x != nil {
		return x.InflightCommandIds
	}
	return nil
}

// Welcome accepts the session.
type Welcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GatewayVersion  string                 `protobuf:"bytes,2,opt,name=gateway_version,json=gatewayVersion,proto3" json:"gateway_version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Seconds between heartbeats the gateway expects.
	HeartbeatIntervalSeconds uint32 `protobuf:"varint,4,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Welcome) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

func (x *Welcome) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Welcome) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

// Heartbeat keeps the session and its PostgreSQL lease alive.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentUnixMs    int64                  `protobuf:"varint,1,opt,name=sent_unix_ms,json=sentUnixMs,proto3" json:"sent_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetSentUnixMs() int64 {
	if x != nil {
		return x.SentUnixMs
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"v\n" +
	"\x0eConnectRequest\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.agent.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04body\"}\n" +
	"\x0fConnectResponse\x12-\n" +
	"\awelcome\x18\x01 \x01(\v2\x11.agent.v1.WelcomeH\x00R\awelcome\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04body\"\xe8\x01\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_release\x18\x04 \x01(\tR\tosRelease\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x120\n" +
	"\x14inflight_command_ids\x18\x06 \x03(\tR\x12inflightCommandIds\"\xba\x01\n" +
	"\aWelcome\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fgateway_version\x18\x02 \x01(\tR\x0egatewayVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x04 \x01(\rR\x18heartbeatIntervalSeconds\"-\n" +
	"\tHeartbeat\x12 \n" +
	"\fsent_unix_ms\x18\x01 \x01(\x03R\n" +
	"sentUnixMs2R\n" +
	"\fAgentService\x12B\n" +
	"\aConnect\x12\x18.agent.v1.ConnectRequest\x1a\x19.agent.v1.ConnectResponse(\x010\x01BAZ?github.com/AxiomOperator/dbr2/internal/agentpb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_v1_agent_proto_goTypes = []any{
	(*ConnectRequest)(nil),  // 0: agent.v1.ConnectRequest
	(*ConnectResponse)(nil), // 1: agent.v1.ConnectResponse
	(*Hello)(nil),           // 2: agent.v1.Hello
	(*Welcome)(nil),         // 3: agent.v1.Welcome
	(*Heartbeat)(nil),       // 4: agent.v1.Heartbeat
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	2, // 0: agent.v1.ConnectRequest.hello:type_name -> agent.v1.Hello
	4, // 1: agent.v1.ConnectRequest.heartbeat:type_name -> agent.v1.Heartbeat
	3, // 2: agent.v1.ConnectResponse.welcome:type_name -> agent.v1.Welcome
	4, // 3: agent.v1.ConnectResponse.heartbeat:type_name -> agent.v1.Heartbeat
	0, // 4: agent.v1.AgentService.Connect:input_type -> agent.v1.ConnectRequest
	1, // 5: agent.v1.AgentService.Connect:output_type -> agent.v1.ConnectResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectRequest_Hello)(nil),
		(*ConnectRequest_Heartbeat)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ConnectResponse_Welcome)(nil),
		(*ConnectResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
