// Code generated by internal/version/gen from the component VERSION files. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0

package version

// components maps each component to MAJOR.MINOR.BUGFIX from its VERSION file.
var components = map[string]string{
	"agent":           "0.1.0",
	"agent-protocol":  "0.1.0",
	"api":             "0.1.0",
	"cli":             "0.1.0",
	"db-schema":       "0.1.0",
	"deployment":      "0.1.0",
	"manifest-schema": "0.1.0",
	"platform":        "0.1.0",
	"reposerver":      "0.1.0",
	"server":          "0.1.0",
	"web":             "0.1.0",
	"worker":          "0.1.0",
}
