// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimRegistrationToken = `-- name: ClaimRegistrationToken :one
UPDATE agent_registration_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now()
RETURNING id, org_id
`

type ClaimRegistrationTokenRow struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// Single use: the conditional update makes concurrent claims race-safe.
func (q *Queries) ClaimRegistrationToken(ctx context.Context, tokenHash []byte) (ClaimRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, claimRegistrationToken, tokenHash)
	var i ClaimRegistrationTokenRow
	err := row.Scan(&i.ID, &i.OrgID)
	return i, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (org_id, hostname, agent_version, protocol_version, os_release, architecture, registration_token_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, hostname, status, status_reason, status_changed_at, status_changed_by, enrolled_at, approved_at, agent_version, protocol_version, os_release, architecture, cert_serial, cert_fingerprint, cert_not_after, last_seen_at, last_latency_ms, docker_reachable, docker_version, health_error, registration_token_id, offline_alerted_at
`

type CreateAgentParams struct {
	OrgID               uuid.UUID
	Hostname            string
	AgentVersion        string
	ProtocolVersion     string
	OsRelease           *string
	Architecture        *string
	RegistrationTokenID *uuid.UUID
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OrgID,
		arg.Hostname,
		arg.AgentVersion,
		arg.ProtocolVersion,
		arg.OsRelease,
		arg.Architecture,
		arg.RegistrationTokenID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Hostname,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.EnrolledAt,
		&i.ApprovedAt,
		&i.AgentVersion,
		&i.ProtocolVersion,
		&i.OsRelease,
		&i.Architecture,
		&i.CertSerial,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.LastSeenAt,
		&i.LastLatencyMs,
		&i.DockerReachable,
		&i.DockerVersion,
		&i.HealthError,
		&i.RegistrationTokenID,
		&i.OfflineAlertedAt,
	)
	return i, err
}

const createAuthority = `-- name: CreateAuthority :exec
INSERT INTO pki_authorities (name, org_id, cert_der, key_enc, fingerprint)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name) DO NOTHING
`

type CreateAuthorityParams struct {
	Name        string
	OrgID       uuid.UUID
	CertDer     []byte
	KeyEnc      []byte
	Fingerprint string
}

func (q *Queries) CreateAuthority(ctx context.Context, arg CreateAuthorityParams) error {
	_, err := q.db.Exec(ctx, createAuthority,
		arg.Name,
		arg.OrgID,
		arg.CertDer,
		arg.KeyEnc,
		arg.Fingerprint,
	)
	return err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :one
INSERT INTO agent_registration_tokens (org_id, token_hash, prefix, description, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, prefix, description, created_at, expires_at
`

type CreateRegistrationTokenParams struct {
	OrgID       uuid.UUID
	TokenHash   []byte
	Prefix      string
	Description string
	CreatedBy   *uuid.UUID
	ExpiresAt   time.Time
}

type CreateRegistrationTokenRow struct {
	ID          uuid.UUID
	Prefix      string
	Description string
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) (CreateRegistrationTokenRow, error) {
	row := q.db.QueryRow(ctx, createRegistrationToken,
		arg.OrgID,
		arg.TokenHash,
		arg.Prefix,
		arg.Description,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateRegistrationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAgentSession = `-- name: DeleteAgentSession :exec
DELETE FROM agent_sessions WHERE agent_id = $1 AND session_id = $2
`

type DeleteAgentSessionParams struct {
	AgentID   uuid.UUID
	SessionID string
}

func (q *Queries) DeleteAgentSession(ctx context.Context, arg DeleteAgentSessionParams) error {
	_, err := q.db.Exec(ctx, deleteAgentSession, arg.AgentID, arg.SessionID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, org_id, hostname, status, status_reason, status_changed_at, status_changed_by, enrolled_at, approved_at, agent_version, protocol_version, os_release, architecture, cert_serial, cert_fingerprint, cert_not_after, last_seen_at, last_latency_ms, docker_reachable, docker_version, health_error, registration_token_id, offline_alerted_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Hostname,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.EnrolledAt,
		&i.ApprovedAt,
		&i.AgentVersion,
		&i.ProtocolVersion,
		&i.OsRelease,
		&i.Architecture,
		&i.CertSerial,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.LastSeenAt,
		&i.LastLatencyMs,
		&i.DockerReachable,
		&i.DockerVersion,
		&i.HealthError,
		&i.RegistrationTokenID,
		&i.OfflineAlertedAt,
	)
	return i, err
}

const getAgentCertificate = `-- name: GetAgentCertificate :one
SELECT serial, agent_id, fingerprint, not_before, not_after, issued_at, revoked_at FROM agent_certificates WHERE serial = $1
`

func (q *Queries) GetAgentCertificate(ctx context.Context, serial string) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, getAgentCertificate, serial)
	var i AgentCertificate
	err := row.Scan(
		&i.Serial,
		&i.AgentID,
		&i.Fingerprint,
		&i.NotBefore,
		&i.NotAfter,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthority = `-- name: GetAuthority :one

SELECT name, org_id, cert_der, key_enc, fingerprint, created_at FROM pki_authorities WHERE name = $1
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetAuthority(ctx context.Context, name string) (PkiAuthority, error) {
	row := q.db.QueryRow(ctx, getAuthority, name)
	var i PkiAuthority
	err := row.Scan(
		&i.Name,
		&i.OrgID,
		&i.CertDer,
		&i.KeyEnc,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentCertificate = `-- name: InsertAgentCertificate :exec
INSERT INTO agent_certificates (serial, agent_id, fingerprint, not_before, not_after)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAgentCertificateParams struct {
	Serial      string
	AgentID     uuid.UUID
	Fingerprint string
	NotBefore   time.Time
	NotAfter    time.Time
}

func (q *Queries) InsertAgentCertificate(ctx context.Context, arg InsertAgentCertificateParams) error {
	_, err := q.db.Exec(ctx, insertAgentCertificate,
		arg.Serial,
		arg.AgentID,
		arg.Fingerprint,
		arg.NotBefore,
		arg.NotAfter,
	)
	return err
}

const listAgentCommands = `-- name: ListAgentCommands :many
SELECT command_id, agent_id, kind, state, error, created_at, updated_at FROM agent_commands WHERE agent_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListAgentCommandsParams struct {
	AgentID uuid.UUID
	Limit   int32
}

func (q *Queries) ListAgentCommands(ctx context.Context, arg ListAgentCommandsParams) ([]AgentCommand, error) {
	rows, err := q.db.Query(ctx, listAgentCommands, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentCommand
	for rows.Next() {
		var i AgentCommand
		if err := rows.Scan(
			&i.CommandID,
			&i.AgentID,
			&i.Kind,
			&i.State,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT agent_id, session_id, gateway_instance, remote_addr, connected_at, last_heartbeat_at FROM agent_sessions
`

func (q *Queries) ListAgentSessions(ctx context.Context) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSession
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.AgentID,
			&i.SessionID,
			&i.GatewayInstance,
			&i.RemoteAddr,
			&i.ConnectedAt,
			&i.LastHeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, org_id, hostname, status, status_reason, status_changed_at, status_changed_by, enrolled_at, approved_at, agent_version, protocol_version, os_release, architecture, cert_serial, cert_fingerprint, cert_not_after, last_seen_at, last_latency_ms, docker_reachable, docker_version, health_error, registration_token_id, offline_alerted_at FROM agents WHERE org_id = $1 ORDER BY hostname, enrolled_at
`

func (q *Queries) ListAgents(ctx context.Context, orgID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Hostname,
			&i.Status,
			&i.StatusReason,
			&i.StatusChangedAt,
			&i.StatusChangedBy,
			&i.EnrolledAt,
			&i.ApprovedAt,
			&i.AgentVersion,
			&i.ProtocolVersion,
			&i.OsRelease,
			&i.Architecture,
			&i.CertSerial,
			&i.CertFingerprint,
			&i.CertNotAfter,
			&i.LastSeenAt,
			&i.LastLatencyMs,
			&i.DockerReachable,
			&i.DockerVersion,
			&i.HealthError,
			&i.RegistrationTokenID,
			&i.OfflineAlertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationTokens = `-- name: ListRegistrationTokens :many
SELECT id, prefix, description, created_by, created_at, expires_at, used_at, used_by_agent, revoked_at
FROM agent_registration_tokens WHERE org_id = $1 ORDER BY created_at DESC LIMIT 200
`

type ListRegistrationTokensRow struct {
	ID          uuid.UUID
	Prefix      string
	Description string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UsedAt      *time.Time
	UsedByAgent *uuid.UUID
	RevokedAt   *time.Time
}

func (q *Queries) ListRegistrationTokens(ctx context.Context, orgID uuid.UUID) ([]ListRegistrationTokensRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationTokens, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationTokensRow
	for rows.Next() {
		var i ListRegistrationTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedByAgent,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgentCertificates = `-- name: RevokeAgentCertificates :exec
UPDATE agent_certificates SET revoked_at = now() WHERE agent_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAgentCertificates(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAgentCertificates, agentID)
	return err
}

const revokeAgentCertificatesExcept = `-- name: RevokeAgentCertificatesExcept :exec
UPDATE agent_certificates SET revoked_at = now() WHERE agent_id = $1 AND serial <> $2 AND revoked_at IS NULL
`

type RevokeAgentCertificatesExceptParams struct {
	AgentID uuid.UUID
	Serial  string
}

func (q *Queries) RevokeAgentCertificatesExcept(ctx context.Context, arg RevokeAgentCertificatesExceptParams) error {
	_, err := q.db.Exec(ctx, revokeAgentCertificatesExcept, arg.AgentID, arg.Serial)
	return err
}

const revokeRegistrationToken = `-- name: RevokeRegistrationToken :execrows
UPDATE agent_registration_tokens SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL AND used_at IS NULL
`

type RevokeRegistrationTokenParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) RevokeRegistrationToken(ctx context.Context, arg RevokeRegistrationTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRegistrationToken, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAgentCertificate = `-- name: SetAgentCertificate :exec
UPDATE agents SET cert_serial = $2, cert_fingerprint = $3, cert_not_after = $4 WHERE id = $1
`

type SetAgentCertificateParams struct {
	ID              uuid.UUID
	CertSerial      *string
	CertFingerprint *string
	CertNotAfter    *time.Time
}

func (q *Queries) SetAgentCertificate(ctx context.Context, arg SetAgentCertificateParams) error {
	_, err := q.db.Exec(ctx, setAgentCertificate,
		arg.ID,
		arg.CertSerial,
		arg.CertFingerprint,
		arg.CertNotAfter,
	)
	return err
}

const setAgentStatus = `-- name: SetAgentStatus :one
UPDATE agents SET status = $2, status_reason = $3, status_changed_at = now(), status_changed_by = $4,
    approved_at = CASE WHEN $2 = 'active' AND approved_at IS NULL THEN now() ELSE approved_at END
WHERE id = $1 AND org_id = $5
RETURNING id, org_id, hostname, status, status_reason, status_changed_at, status_changed_by, enrolled_at, approved_at, agent_version, protocol_version, os_release, architecture, cert_serial, cert_fingerprint, cert_not_after, last_seen_at, last_latency_ms, docker_reachable, docker_version, health_error, registration_token_id, offline_alerted_at
`

type SetAgentStatusParams struct {
	ID              uuid.UUID
	Status          string
	StatusReason    *string
	StatusChangedBy *uuid.UUID
	OrgID           uuid.UUID
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentStatus,
		arg.ID,
		arg.Status,
		arg.StatusReason,
		arg.StatusChangedBy,
		arg.OrgID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Hostname,
		&i.Status,
		&i.StatusReason,
		&i.StatusChangedAt,
		&i.StatusChangedBy,
		&i.EnrolledAt,
		&i.ApprovedAt,
		&i.AgentVersion,
		&i.ProtocolVersion,
		&i.OsRelease,
		&i.Architecture,
		&i.CertSerial,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.LastSeenAt,
		&i.LastLatencyMs,
		&i.DockerReachable,
		&i.DockerVersion,
		&i.HealthError,
		&i.RegistrationTokenID,
		&i.OfflineAlertedAt,
	)
	return i, err
}

const setRegistrationTokenAgent = `-- name: SetRegistrationTokenAgent :exec
UPDATE agent_registration_tokens SET used_by_agent = $2 WHERE id = $1
`

type SetRegistrationTokenAgentParams struct {
	ID          uuid.UUID
	UsedByAgent *uuid.UUID
}

func (q *Queries) SetRegistrationTokenAgent(ctx context.Context, arg SetRegistrationTokenAgentParams) error {
	_, err := q.db.Exec(ctx, setRegistrationTokenAgent, arg.ID, arg.UsedByAgent)
	return err
}

const touchAgentSession = `-- name: TouchAgentSession :exec
UPDATE agent_sessions SET last_heartbeat_at = now() WHERE agent_id = $1 AND session_id = $2
`

type TouchAgentSessionParams struct {
	AgentID   uuid.UUID
	SessionID string
}

func (q *Queries) TouchAgentSession(ctx context.Context, arg TouchAgentSessionParams) error {
	_, err := q.db.Exec(ctx, touchAgentSession, arg.AgentID, arg.SessionID)
	return err
}

const updateAgentHealth = `-- name: UpdateAgentHealth :exec
UPDATE agents SET docker_reachable = $2, docker_version = $3, health_error = $4, last_seen_at = now()
WHERE id = $1
`

type UpdateAgentHealthParams struct {
	ID              uuid.UUID
	DockerReachable *bool
	DockerVersion   *string
	HealthError     *string
}

func (q *Queries) UpdateAgentHealth(ctx context.Context, arg UpdateAgentHealthParams) error {
	_, err := q.db.Exec(ctx, updateAgentHealth,
		arg.ID,
		arg.DockerReachable,
		arg.DockerVersion,
		arg.HealthError,
	)
	return err
}

const updateAgentHello = `-- name: UpdateAgentHello :exec
UPDATE agents SET agent_version = $2, protocol_version = $3, os_release = $4, architecture = $5,
    hostname = $6, last_seen_at = now()
WHERE id = $1
`

type UpdateAgentHelloParams struct {
	ID              uuid.UUID
	AgentVersion    string
	ProtocolVersion string
	OsRelease       *string
	Architecture    *string
	Hostname        string
}

func (q *Queries) UpdateAgentHello(ctx context.Context, arg UpdateAgentHelloParams) error {
	_, err := q.db.Exec(ctx, updateAgentHello,
		arg.ID,
		arg.AgentVersion,
		arg.ProtocolVersion,
		arg.OsRelease,
		arg.Architecture,
		arg.Hostname,
	)
	return err
}

const updateAgentLatency = `-- name: UpdateAgentLatency :exec
UPDATE agents SET last_latency_ms = $2, last_seen_at = now() WHERE id = $1
`

type UpdateAgentLatencyParams struct {
	ID            uuid.UUID
	LastLatencyMs *int32
}

func (q *Queries) UpdateAgentLatency(ctx context.Context, arg UpdateAgentLatencyParams) error {
	_, err := q.db.Exec(ctx, updateAgentLatency, arg.ID, arg.LastLatencyMs)
	return err
}

const upsertAgentCommand = `-- name: UpsertAgentCommand :exec
INSERT INTO agent_commands (command_id, agent_id, kind, state, error)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (command_id) DO UPDATE SET state = EXCLUDED.state, error = EXCLUDED.error, updated_at = now()
`

type UpsertAgentCommandParams struct {
	CommandID string
	AgentID   uuid.UUID
	Kind      string
	State     string
	Error     *string
}

func (q *Queries) UpsertAgentCommand(ctx context.Context, arg UpsertAgentCommandParams) error {
	_, err := q.db.Exec(ctx, upsertAgentCommand,
		arg.CommandID,
		arg.AgentID,
		arg.Kind,
		arg.State,
		arg.Error,
	)
	return err
}

const upsertAgentSession = `-- name: UpsertAgentSession :exec
INSERT INTO agent_sessions (agent_id, session_id, gateway_instance, remote_addr)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id) DO UPDATE SET session_id = EXCLUDED.session_id, gateway_instance = EXCLUDED.gateway_instance,
    remote_addr = EXCLUDED.remote_addr, connected_at = now(), last_heartbeat_at = now()
`

type UpsertAgentSessionParams struct {
	AgentID         uuid.UUID
	SessionID       string
	GatewayInstance string
	RemoteAddr      *string
}

func (q *Queries) UpsertAgentSession(ctx context.Context, arg UpsertAgentSessionParams) error {
	_, err := q.db.Exec(ctx, upsertAgentSession,
		arg.AgentID,
		arg.SessionID,
		arg.GatewayInstance,
		arg.RemoteAddr,
	)
	return err
}
