// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notification_outbox (org_id, event_type, severity, payload)
VALUES ($1, $2, $3, $4)
`

type EnqueueNotificationParams struct {
	OrgID     uuid.UUID
	EventType string
	Severity  string
	Payload   json.RawMessage
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.OrgID,
		arg.EventType,
		arg.Severity,
		arg.Payload,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one

INSERT INTO audit_events (
    org_id, event_type, actor_user_id, actor_display, actor_kind, source_ip,
    target_type, target_id, reason, result, details, before_state, after_state,
    request_id, trace_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING seq, event_id, occurred_at
`

type InsertAuditEventParams struct {
	OrgID        uuid.UUID
	EventType    string
	ActorUserID  *uuid.UUID
	ActorDisplay string
	ActorKind    string
	SourceIp     *netip.Addr
	TargetType   *string
	TargetID     *string
	Reason       *string
	Result       string
	Details      json.RawMessage
	BeforeState  json.RawMessage
	AfterState   json.RawMessage
	RequestID    *string
	TraceID      *string
}

type InsertAuditEventRow struct {
	Seq        int64
	EventID    uuid.UUID
	OccurredAt time.Time
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.OrgID,
		arg.EventType,
		arg.ActorUserID,
		arg.ActorDisplay,
		arg.ActorKind,
		arg.SourceIp,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Result,
		arg.Details,
		arg.BeforeState,
		arg.AfterState,
		arg.RequestID,
		arg.TraceID,
	)
	var i InsertAuditEventRow
	err := row.Scan(&i.Seq, &i.EventID, &i.OccurredAt)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT seq, event_id, org_id, occurred_at, event_type, actor_user_id, actor_display, actor_kind, source_ip, target_type, target_id, reason, result, details, before_state, after_state, request_id, trace_id FROM audit_events
WHERE org_id = $1
  AND ($2::bigint IS NULL OR seq < $2)
  AND ($3::text IS NULL OR event_type = $3)
ORDER BY seq DESC
LIMIT $4
`

type ListAuditEventsParams struct {
	OrgID     uuid.UUID
	BeforeSeq *int64
	EventType *string
	MaxRows   int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.OrgID,
		arg.BeforeSeq,
		arg.EventType,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.EventID,
			&i.OrgID,
			&i.OccurredAt,
			&i.EventType,
			&i.ActorUserID,
			&i.ActorDisplay,
			&i.ActorKind,
			&i.SourceIp,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Result,
			&i.Details,
			&i.BeforeState,
			&i.AfterState,
			&i.RequestID,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
