// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const acknowledgeNotification = `-- name: AcknowledgeNotification :execrows
UPDATE notification_outbox SET acknowledged_at = now(), acknowledged_by = $3
WHERE id = $1 AND org_id = $2 AND acknowledged_at IS NULL
`

type AcknowledgeNotificationParams struct {
	ID             int64
	OrgID          uuid.UUID
	AcknowledgedBy *uuid.UUID
}

func (q *Queries) AcknowledgeNotification(ctx context.Context, arg AcknowledgeNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeNotification, arg.ID, arg.OrgID, arg.AcknowledgedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const commitRecoveryPoint = `-- name: CommitRecoveryPoint :one
UPDATE recovery_points SET state = 'committed', status = $2, consistency_mode = $3, consistency_point = $4,
    crash_consistent_only = $5, size_bytes = $6, component_count = $7, manifest = $8,
    manifest_snapshot_id = $9, error = NULL, committed_at = coalesce(committed_at, now()), updated_at = now()
WHERE id = $1
RETURNING id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at
`

type CommitRecoveryPointParams struct {
	ID                  string
	Status              *string
	ConsistencyMode     string
	ConsistencyPoint    *time.Time
	CrashConsistentOnly bool
	SizeBytes           int64
	ComponentCount      int32
	Manifest            json.RawMessage
	ManifestSnapshotID  *string
}

func (q *Queries) CommitRecoveryPoint(ctx context.Context, arg CommitRecoveryPointParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, commitRecoveryPoint,
		arg.ID,
		arg.Status,
		arg.ConsistencyMode,
		arg.ConsistencyPoint,
		arg.CrashConsistentOnly,
		arg.SizeBytes,
		arg.ComponentCount,
		arg.Manifest,
		arg.ManifestSnapshotID,
	)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecoveryPoint = `-- name: CreateRecoveryPoint :one

INSERT INTO recovery_points (id, org_id, repository_id, application_id, application_name, agent_id, hostname,
    consistency_mode, trigger, requested_by, workflow_id, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET updated_at = now()
RETURNING id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at
`

type CreateRecoveryPointParams struct {
	ID              string
	OrgID           uuid.UUID
	RepositoryID    uuid.UUID
	ApplicationID   uuid.UUID
	ApplicationName string
	AgentID         uuid.UUID
	Hostname        string
	ConsistencyMode string
	Trigger         string
	RequestedBy     *uuid.UUID
	WorkflowID      string
	RunID           string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateRecoveryPoint(ctx context.Context, arg CreateRecoveryPointParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, createRecoveryPoint,
		arg.ID,
		arg.OrgID,
		arg.RepositoryID,
		arg.ApplicationID,
		arg.ApplicationName,
		arg.AgentID,
		arg.Hostname,
		arg.ConsistencyMode,
		arg.Trigger,
		arg.RequestedBy,
		arg.WorkflowID,
		arg.RunID,
	)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failRecoveryPoint = `-- name: FailRecoveryPoint :one
UPDATE recovery_points SET state = 'failed', error = $2, updated_at = now()
WHERE id = $1 AND state = 'pending'
RETURNING id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at
`

type FailRecoveryPointParams struct {
	ID    string
	Error *string
}

func (q *Queries) FailRecoveryPoint(ctx context.Context, arg FailRecoveryPointParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, failRecoveryPoint, arg.ID, arg.Error)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationBackupSettings = `-- name: GetApplicationBackupSettings :one
SELECT application_id, repository_id, consistency_mode, max_quiesce_seconds, pre_hooks, post_hooks, optional_components, excluded_components, updated_by, updated_at FROM application_backup_settings WHERE application_id = $1
`

func (q *Queries) GetApplicationBackupSettings(ctx context.Context, applicationID uuid.UUID) (ApplicationBackupSetting, error) {
	row := q.db.QueryRow(ctx, getApplicationBackupSettings, applicationID)
	var i ApplicationBackupSetting
	err := row.Scan(
		&i.ApplicationID,
		&i.RepositoryID,
		&i.ConsistencyMode,
		&i.MaxQuiesceSeconds,
		&i.PreHooks,
		&i.PostHooks,
		&i.OptionalComponents,
		&i.ExcludedComponents,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostSettings = `-- name: GetHostSettings :one
SELECT agent_id, max_concurrent_jobs, backup_window_start, backup_window_end, backup_window_timezone, updated_by, updated_at FROM host_settings WHERE agent_id = $1
`

func (q *Queries) GetHostSettings(ctx context.Context, agentID uuid.UUID) (HostSetting, error) {
	row := q.db.QueryRow(ctx, getHostSettings, agentID)
	var i HostSetting
	err := row.Scan(
		&i.AgentID,
		&i.MaxConcurrentJobs,
		&i.BackupWindowStart,
		&i.BackupWindowEnd,
		&i.BackupWindowTimezone,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRecoveryPointForRun = `-- name: GetPendingRecoveryPointForRun :one
SELECT id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at FROM recovery_points WHERE workflow_id = $1 AND run_id = $2 AND state = 'pending'
ORDER BY created_at DESC LIMIT 1
`

type GetPendingRecoveryPointForRunParams struct {
	WorkflowID string
	RunID      string
}

func (q *Queries) GetPendingRecoveryPointForRun(ctx context.Context, arg GetPendingRecoveryPointForRunParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, getPendingRecoveryPointForRun, arg.WorkflowID, arg.RunID)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecoveryPoint = `-- name: GetRecoveryPoint :one
SELECT id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at FROM recovery_points WHERE id = $1 AND org_id = $2
`

type GetRecoveryPointParams struct {
	ID    string
	OrgID uuid.UUID
}

func (q *Queries) GetRecoveryPoint(ctx context.Context, arg GetRecoveryPointParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, getRecoveryPoint, arg.ID, arg.OrgID)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecoveryPointByID = `-- name: GetRecoveryPointByID :one
SELECT id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at FROM recovery_points WHERE id = $1
`

func (q *Queries) GetRecoveryPointByID(ctx context.Context, id string) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, getRecoveryPointByID, id)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notification_outbox (org_id, severity, event_type, target_type, target_id, message, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNotificationParams struct {
	OrgID      uuid.UUID
	Severity   string
	EventType  string
	TargetType *string
	TargetID   *string
	Message    string
	Payload    json.RawMessage
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.OrgID,
		arg.Severity,
		arg.EventType,
		arg.TargetType,
		arg.TargetID,
		arg.Message,
		arg.Payload,
	)
	return err
}

const lastCommittedRecoveryPoint = `-- name: LastCommittedRecoveryPoint :one
SELECT id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at FROM recovery_points WHERE application_id = $1 AND state = 'committed'
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LastCommittedRecoveryPoint(ctx context.Context, applicationID uuid.UUID) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, lastCommittedRecoveryPoint, applicationID)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, org_id, event_type, severity, payload, created_at, delivered_at, target_type, target_id, message, acknowledged_at, acknowledged_by FROM notification_outbox WHERE org_id = $1
  AND (NOT $3::boolean OR acknowledged_at IS NULL)
ORDER BY created_at DESC LIMIT $2
`

type ListNotificationsParams struct {
	OrgID    uuid.UUID
	Limit    int32
	OpenOnly bool
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.OrgID, arg.Limit, arg.OpenOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EventType,
			&i.Severity,
			&i.Payload,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.TargetType,
			&i.TargetID,
			&i.Message,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryPoints = `-- name: ListRecoveryPoints :many
SELECT id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at FROM recovery_points
WHERE org_id = $1
  AND ($3::uuid IS NULL OR application_id = $3)
  AND ($4::text IS NULL OR state = $4)
ORDER BY created_at DESC
LIMIT $2
`

type ListRecoveryPointsParams struct {
	OrgID         uuid.UUID
	Limit         int32
	ApplicationID *uuid.UUID
	State         *string
}

func (q *Queries) ListRecoveryPoints(ctx context.Context, arg ListRecoveryPointsParams) ([]RecoveryPoint, error) {
	rows, err := q.db.Query(ctx, listRecoveryPoints,
		arg.OrgID,
		arg.Limit,
		arg.ApplicationID,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryPoint
	for rows.Next() {
		var i RecoveryPoint
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RepositoryID,
			&i.ApplicationID,
			&i.ApplicationName,
			&i.AgentID,
			&i.Hostname,
			&i.State,
			&i.Status,
			&i.Verification,
			&i.ConsistencyMode,
			&i.ConsistencyPoint,
			&i.CrashConsistentOnly,
			&i.Trigger,
			&i.RequestedBy,
			&i.WorkflowID,
			&i.RunID,
			&i.SizeBytes,
			&i.ComponentCount,
			&i.Manifest,
			&i.ManifestSnapshotID,
			&i.Error,
			&i.CreatedAt,
			&i.CommittedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingRecoveryPoints = `-- name: MarkMissingRecoveryPoints :execrows
UPDATE recovery_points SET state = 'missing', updated_at = now()
WHERE repository_id = $1 AND state = 'committed' AND NOT (id = ANY($2::text[]))
`

type MarkMissingRecoveryPointsParams struct {
	RepositoryID uuid.UUID
	PresentIds   []string
}

func (q *Queries) MarkMissingRecoveryPoints(ctx context.Context, arg MarkMissingRecoveryPointsParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMissingRecoveryPoints, arg.RepositoryID, arg.PresentIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertApplicationBackupSettings = `-- name: UpsertApplicationBackupSettings :one
INSERT INTO application_backup_settings (application_id, repository_id, consistency_mode, max_quiesce_seconds,
    pre_hooks, post_hooks, optional_components, excluded_components, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (application_id) DO UPDATE SET repository_id = EXCLUDED.repository_id,
    consistency_mode = EXCLUDED.consistency_mode, max_quiesce_seconds = EXCLUDED.max_quiesce_seconds,
    pre_hooks = EXCLUDED.pre_hooks, post_hooks = EXCLUDED.post_hooks,
    optional_components = EXCLUDED.optional_components, excluded_components = EXCLUDED.excluded_components,
    updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING application_id, repository_id, consistency_mode, max_quiesce_seconds, pre_hooks, post_hooks, optional_components, excluded_components, updated_by, updated_at
`

type UpsertApplicationBackupSettingsParams struct {
	ApplicationID      uuid.UUID
	RepositoryID       *uuid.UUID
	ConsistencyMode    *string
	MaxQuiesceSeconds  int32
	PreHooks           json.RawMessage
	PostHooks          json.RawMessage
	OptionalComponents []string
	ExcludedComponents []string
	UpdatedBy          *uuid.UUID
}

func (q *Queries) UpsertApplicationBackupSettings(ctx context.Context, arg UpsertApplicationBackupSettingsParams) (ApplicationBackupSetting, error) {
	row := q.db.QueryRow(ctx, upsertApplicationBackupSettings,
		arg.ApplicationID,
		arg.RepositoryID,
		arg.ConsistencyMode,
		arg.MaxQuiesceSeconds,
		arg.PreHooks,
		arg.PostHooks,
		arg.OptionalComponents,
		arg.ExcludedComponents,
		arg.UpdatedBy,
	)
	var i ApplicationBackupSetting
	err := row.Scan(
		&i.ApplicationID,
		&i.RepositoryID,
		&i.ConsistencyMode,
		&i.MaxQuiesceSeconds,
		&i.PreHooks,
		&i.PostHooks,
		&i.OptionalComponents,
		&i.ExcludedComponents,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHostSettings = `-- name: UpsertHostSettings :one
INSERT INTO host_settings (agent_id, max_concurrent_jobs, backup_window_start, backup_window_end,
    backup_window_timezone, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (agent_id) DO UPDATE SET max_concurrent_jobs = EXCLUDED.max_concurrent_jobs,
    backup_window_start = EXCLUDED.backup_window_start, backup_window_end = EXCLUDED.backup_window_end,
    backup_window_timezone = EXCLUDED.backup_window_timezone, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING agent_id, max_concurrent_jobs, backup_window_start, backup_window_end, backup_window_timezone, updated_by, updated_at
`

type UpsertHostSettingsParams struct {
	AgentID              uuid.UUID
	MaxConcurrentJobs    int32
	BackupWindowStart    *int32
	BackupWindowEnd      *int32
	BackupWindowTimezone string
	UpdatedBy            *uuid.UUID
}

func (q *Queries) UpsertHostSettings(ctx context.Context, arg UpsertHostSettingsParams) (HostSetting, error) {
	row := q.db.QueryRow(ctx, upsertHostSettings,
		arg.AgentID,
		arg.MaxConcurrentJobs,
		arg.BackupWindowStart,
		arg.BackupWindowEnd,
		arg.BackupWindowTimezone,
		arg.UpdatedBy,
	)
	var i HostSetting
	err := row.Scan(
		&i.AgentID,
		&i.MaxConcurrentJobs,
		&i.BackupWindowStart,
		&i.BackupWindowEnd,
		&i.BackupWindowTimezone,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIndexedRecoveryPoint = `-- name: UpsertIndexedRecoveryPoint :exec
INSERT INTO recovery_points (id, org_id, repository_id, application_id, application_name, agent_id, hostname,
    state, status, consistency_mode, consistency_point, crash_consistent_only, trigger, workflow_id, run_id,
    size_bytes, component_count, manifest, manifest_snapshot_id, created_at, committed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'committed', $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $19)
ON CONFLICT (id) DO UPDATE SET state = 'committed', status = EXCLUDED.status,
    repository_id = EXCLUDED.repository_id, consistency_mode = EXCLUDED.consistency_mode,
    consistency_point = EXCLUDED.consistency_point, crash_consistent_only = EXCLUDED.crash_consistent_only,
    size_bytes = EXCLUDED.size_bytes, component_count = EXCLUDED.component_count, manifest = EXCLUDED.manifest,
    manifest_snapshot_id = EXCLUDED.manifest_snapshot_id, error = NULL,
    committed_at = coalesce(recovery_points.committed_at, EXCLUDED.committed_at), updated_at = now()
`

type UpsertIndexedRecoveryPointParams struct {
	ID                  string
	OrgID               uuid.UUID
	RepositoryID        uuid.UUID
	ApplicationID       uuid.UUID
	ApplicationName     string
	AgentID             uuid.UUID
	Hostname            string
	Status              *string
	ConsistencyMode     string
	ConsistencyPoint    *time.Time
	CrashConsistentOnly bool
	Trigger             string
	WorkflowID          string
	RunID               string
	SizeBytes           int64
	ComponentCount      int32
	Manifest            json.RawMessage
	ManifestSnapshotID  *string
	CreatedAt           time.Time
}

// Reindexing (ADR-0003): the Repository wins.
func (q *Queries) UpsertIndexedRecoveryPoint(ctx context.Context, arg UpsertIndexedRecoveryPointParams) error {
	_, err := q.db.Exec(ctx, upsertIndexedRecoveryPoint,
		arg.ID,
		arg.OrgID,
		arg.RepositoryID,
		arg.ApplicationID,
		arg.ApplicationName,
		arg.AgentID,
		arg.Hostname,
		arg.Status,
		arg.ConsistencyMode,
		arg.ConsistencyPoint,
		arg.CrashConsistentOnly,
		arg.Trigger,
		arg.WorkflowID,
		arg.RunID,
		arg.SizeBytes,
		arg.ComponentCount,
		arg.Manifest,
		arg.ManifestSnapshotID,
		arg.CreatedAt,
	)
	return err
}
