// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceTOTPStep = `-- name: AdvanceTOTPStep :execrows
UPDATE local_credentials SET totp_last_step = $2 WHERE user_id = $1 AND totp_last_step < $2
`

type AdvanceTOTPStepParams struct {
	UserID       uuid.UUID
	TotpLastStep int64
}

// Rejects replay: a TOTP time step can be used at most once.
func (q *Queries) AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceTOTPStep, arg.UserID, arg.TotpLastStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createLocalCredential = `-- name: CreateLocalCredential :exec

INSERT INTO local_credentials (user_id, password_hash, must_change_password)
VALUES ($1, $2, $3)
`

type CreateLocalCredentialParams struct {
	UserID             uuid.UUID
	PasswordHash       string
	MustChangePassword bool
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateLocalCredential(ctx context.Context, arg CreateLocalCredentialParams) error {
	_, err := q.db.Exec(ctx, createLocalCredential, arg.UserID, arg.PasswordHash, arg.MustChangePassword)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE local_credentials
SET totp_secret_enc = NULL, totp_pending_secret_enc = NULL, totp_enabled = false, totp_last_step = 0
WHERE user_id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, userID)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE local_credentials
SET totp_secret_enc = totp_pending_secret_enc, totp_pending_secret_enc = NULL,
    totp_enabled = true, totp_last_step = $2
WHERE user_id = $1 AND totp_pending_secret_enc IS NOT NULL
`

type EnableTOTPParams struct {
	UserID       uuid.UUID
	TotpLastStep int64
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.Exec(ctx, enableTOTP, arg.UserID, arg.TotpLastStep)
	return err
}

const getLocalCredential = `-- name: GetLocalCredential :one
SELECT user_id, password_hash, password_changed_at, must_change_password, failed_attempts, locked_until, totp_secret_enc, totp_pending_secret_enc, totp_enabled, totp_last_step FROM local_credentials WHERE user_id = $1
`

func (q *Queries) GetLocalCredential(ctx context.Context, userID uuid.UUID) (LocalCredential, error) {
	row := q.db.QueryRow(ctx, getLocalCredential, userID)
	var i LocalCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.TotpSecretEnc,
		&i.TotpPendingSecretEnc,
		&i.TotpEnabled,
		&i.TotpLastStep,
	)
	return i, err
}

const getLocalCredentialForUpdate = `-- name: GetLocalCredentialForUpdate :one
SELECT user_id, password_hash, password_changed_at, must_change_password, failed_attempts, locked_until, totp_secret_enc, totp_pending_secret_enc, totp_enabled, totp_last_step FROM local_credentials WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetLocalCredentialForUpdate(ctx context.Context, userID uuid.UUID) (LocalCredential, error) {
	row := q.db.QueryRow(ctx, getLocalCredentialForUpdate, userID)
	var i LocalCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.TotpSecretEnc,
		&i.TotpPendingSecretEnc,
		&i.TotpEnabled,
		&i.TotpLastStep,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE local_credentials SET failed_attempts = $2, locked_until = $3 WHERE user_id = $1
`

type RecordLoginFailureParams struct {
	UserID         uuid.UUID
	FailedAttempts int32
	LockedUntil    *time.Time
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, arg.UserID, arg.FailedAttempts, arg.LockedUntil)
	return err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
UPDATE local_credentials SET failed_attempts = 0, locked_until = NULL WHERE user_id = $1
`

func (q *Queries) ResetLoginFailures(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginFailures, userID)
	return err
}

const setPendingTOTP = `-- name: SetPendingTOTP :exec
UPDATE local_credentials SET totp_pending_secret_enc = $2 WHERE user_id = $1
`

type SetPendingTOTPParams struct {
	UserID               uuid.UUID
	TotpPendingSecretEnc []byte
}

func (q *Queries) SetPendingTOTP(ctx context.Context, arg SetPendingTOTPParams) error {
	_, err := q.db.Exec(ctx, setPendingTOTP, arg.UserID, arg.TotpPendingSecretEnc)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE local_credentials
SET password_hash = $2, must_change_password = $3, password_changed_at = now(),
    failed_attempts = 0, locked_until = NULL
WHERE user_id = $1
`

type UpdatePasswordParams struct {
	UserID             uuid.UUID
	PasswordHash       string
	MustChangePassword bool
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.UserID, arg.PasswordHash, arg.MustChangePassword)
	return err
}
