// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createManualApplication = `-- name: CreateManualApplication :one
INSERT INTO applications (org_id, agent_id, key, kind, name, manual_containers)
VALUES ($1, $2, $3, 'manual', $4, $5)
RETURNING id, org_id, agent_id, key, kind, name, display_name, owner, environment, criticality, manual_containers, first_seen_at, last_seen_at, missing_since, created_at, updated_at, policy_id
`

type CreateManualApplicationParams struct {
	OrgID            uuid.UUID
	AgentID          uuid.UUID
	Key              string
	Name             string
	ManualContainers []string
}

func (q *Queries) CreateManualApplication(ctx context.Context, arg CreateManualApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createManualApplication,
		arg.OrgID,
		arg.AgentID,
		arg.Key,
		arg.Name,
		arg.ManualContainers,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.Key,
		&i.Kind,
		&i.Name,
		&i.DisplayName,
		&i.Owner,
		&i.Environment,
		&i.Criticality,
		&i.ManualContainers,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.MissingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolicyID,
	)
	return i, err
}

const deleteContainerApplications = `-- name: DeleteContainerApplications :exec
DELETE FROM applications WHERE agent_id = $1 AND kind = 'container' AND key = ANY($2::text[])
`

type DeleteContainerApplicationsParams struct {
	AgentID uuid.UUID
	Keys    []string
}

// Standalone container applications claimed by a manual application.
func (q *Queries) DeleteContainerApplications(ctx context.Context, arg DeleteContainerApplicationsParams) error {
	_, err := q.db.Exec(ctx, deleteContainerApplications, arg.AgentID, arg.Keys)
	return err
}

const deleteManualApplication = `-- name: DeleteManualApplication :execrows
DELETE FROM applications WHERE id = $1 AND org_id = $2 AND kind = 'manual'
`

type DeleteManualApplicationParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteManualApplication(ctx context.Context, arg DeleteManualApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManualApplication, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT a.id, a.org_id, a.agent_id, a.key, a.kind, a.name, a.display_name, a.owner, a.environment, a.criticality, a.manual_containers, a.first_seen_at, a.last_seen_at, a.missing_since, a.created_at, a.updated_at, a.policy_id, g.hostname FROM applications a JOIN agents g ON g.id = a.agent_id
WHERE a.id = $1 AND a.org_id = $2
`

type GetApplicationParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetApplicationRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	AgentID          uuid.UUID
	Key              string
	Kind             string
	Name             string
	DisplayName      *string
	Owner            *string
	Environment      *string
	Criticality      *string
	ManualContainers []string
	FirstSeenAt      time.Time
	LastSeenAt       time.Time
	MissingSince     *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	PolicyID         *uuid.UUID
	Hostname         string
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.ID, arg.OrgID)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.Key,
		&i.Kind,
		&i.Name,
		&i.DisplayName,
		&i.Owner,
		&i.Environment,
		&i.Criticality,
		&i.ManualContainers,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.MissingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolicyID,
		&i.Hostname,
	)
	return i, err
}

const getInventorySnapshot = `-- name: GetInventorySnapshot :one
SELECT agent_id, org_id, schema_version, collected_at, received_at, data FROM inventory_snapshots WHERE agent_id = $1
`

func (q *Queries) GetInventorySnapshot(ctx context.Context, agentID uuid.UUID) (InventorySnapshot, error) {
	row := q.db.QueryRow(ctx, getInventorySnapshot, agentID)
	var i InventorySnapshot
	err := row.Scan(
		&i.AgentID,
		&i.OrgID,
		&i.SchemaVersion,
		&i.CollectedAt,
		&i.ReceivedAt,
		&i.Data,
	)
	return i, err
}

const listAgentApplications = `-- name: ListAgentApplications :many
SELECT id, org_id, agent_id, key, kind, name, display_name, owner, environment, criticality, manual_containers, first_seen_at, last_seen_at, missing_since, created_at, updated_at, policy_id FROM applications WHERE agent_id = $1
`

func (q *Queries) ListAgentApplications(ctx context.Context, agentID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listAgentApplications, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AgentID,
			&i.Key,
			&i.Kind,
			&i.Name,
			&i.DisplayName,
			&i.Owner,
			&i.Environment,
			&i.Criticality,
			&i.ManualContainers,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.MissingSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PolicyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT a.id, a.org_id, a.agent_id, a.key, a.kind, a.name, a.display_name, a.owner, a.environment, a.criticality, a.manual_containers, a.first_seen_at, a.last_seen_at, a.missing_since, a.created_at, a.updated_at, a.policy_id, g.hostname FROM applications a JOIN agents g ON g.id = a.agent_id
WHERE a.org_id = $1 ORDER BY lower(coalesce(a.display_name, a.name)), g.hostname
`

type ListApplicationsRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	AgentID          uuid.UUID
	Key              string
	Kind             string
	Name             string
	DisplayName      *string
	Owner            *string
	Environment      *string
	Criticality      *string
	ManualContainers []string
	FirstSeenAt      time.Time
	LastSeenAt       time.Time
	MissingSince     *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	PolicyID         *uuid.UUID
	Hostname         string
}

func (q *Queries) ListApplications(ctx context.Context, orgID uuid.UUID) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AgentID,
			&i.Key,
			&i.Kind,
			&i.Name,
			&i.DisplayName,
			&i.Owner,
			&i.Environment,
			&i.Criticality,
			&i.ManualContainers,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.MissingSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PolicyID,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markApplicationsMissing = `-- name: MarkApplicationsMissing :exec
UPDATE applications SET missing_since = coalesce(missing_since, $3), updated_at = now()
WHERE agent_id = $1 AND kind <> 'manual' AND NOT (key = ANY($4::text[])) AND missing_since IS NULL
  AND $2::boolean
`

type MarkApplicationsMissingParams struct {
	AgentID      uuid.UUID
	Column2      bool
	MissingSince *time.Time
	PresentKeys  []string
}

func (q *Queries) MarkApplicationsMissing(ctx context.Context, arg MarkApplicationsMissingParams) error {
	_, err := q.db.Exec(ctx, markApplicationsMissing,
		arg.AgentID,
		arg.Column2,
		arg.MissingSince,
		arg.PresentKeys,
	)
	return err
}

const updateApplicationMetadata = `-- name: UpdateApplicationMetadata :one
UPDATE applications SET display_name = $3, owner = $4, environment = $5, criticality = $6, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, agent_id, key, kind, name, display_name, owner, environment, criticality, manual_containers, first_seen_at, last_seen_at, missing_since, created_at, updated_at, policy_id
`

type UpdateApplicationMetadataParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	DisplayName *string
	Owner       *string
	Environment *string
	Criticality *string
}

func (q *Queries) UpdateApplicationMetadata(ctx context.Context, arg UpdateApplicationMetadataParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationMetadata,
		arg.ID,
		arg.OrgID,
		arg.DisplayName,
		arg.Owner,
		arg.Environment,
		arg.Criticality,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.Key,
		&i.Kind,
		&i.Name,
		&i.DisplayName,
		&i.Owner,
		&i.Environment,
		&i.Criticality,
		&i.ManualContainers,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.MissingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolicyID,
	)
	return i, err
}

const updateManualApplication = `-- name: UpdateManualApplication :one
UPDATE applications SET name = $3, manual_containers = $4, updated_at = now()
WHERE id = $1 AND org_id = $2 AND kind = 'manual'
RETURNING id, org_id, agent_id, key, kind, name, display_name, owner, environment, criticality, manual_containers, first_seen_at, last_seen_at, missing_since, created_at, updated_at, policy_id
`

type UpdateManualApplicationParams struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Name             string
	ManualContainers []string
}

func (q *Queries) UpdateManualApplication(ctx context.Context, arg UpdateManualApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateManualApplication,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ManualContainers,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AgentID,
		&i.Key,
		&i.Kind,
		&i.Name,
		&i.DisplayName,
		&i.Owner,
		&i.Environment,
		&i.Criticality,
		&i.ManualContainers,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.MissingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolicyID,
	)
	return i, err
}

const upsertDiscoveredApplication = `-- name: UpsertDiscoveredApplication :exec
INSERT INTO applications (org_id, agent_id, key, kind, name, last_seen_at, missing_since)
VALUES ($1, $2, $3, $4, $5, $6, NULL)
ON CONFLICT (agent_id, key) DO UPDATE SET name = EXCLUDED.name, last_seen_at = EXCLUDED.last_seen_at,
    missing_since = NULL, updated_at = now()
`

type UpsertDiscoveredApplicationParams struct {
	OrgID      uuid.UUID
	AgentID    uuid.UUID
	Key        string
	Kind       string
	Name       string
	LastSeenAt time.Time
}

func (q *Queries) UpsertDiscoveredApplication(ctx context.Context, arg UpsertDiscoveredApplicationParams) error {
	_, err := q.db.Exec(ctx, upsertDiscoveredApplication,
		arg.OrgID,
		arg.AgentID,
		arg.Key,
		arg.Kind,
		arg.Name,
		arg.LastSeenAt,
	)
	return err
}

const upsertInventorySnapshot = `-- name: UpsertInventorySnapshot :exec

INSERT INTO inventory_snapshots (agent_id, org_id, schema_version, collected_at, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (agent_id) DO UPDATE SET schema_version = EXCLUDED.schema_version,
    collected_at = EXCLUDED.collected_at, data = EXCLUDED.data, received_at = now()
WHERE inventory_snapshots.collected_at <= EXCLUDED.collected_at
`

type UpsertInventorySnapshotParams struct {
	AgentID       uuid.UUID
	OrgID         uuid.UUID
	SchemaVersion int32
	CollectedAt   time.Time
	Data          json.RawMessage
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) UpsertInventorySnapshot(ctx context.Context, arg UpsertInventorySnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertInventorySnapshot,
		arg.AgentID,
		arg.OrgID,
		arg.SchemaVersion,
		arg.CollectedAt,
		arg.Data,
	)
	return err
}
