// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  []byte
	Prefix     string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type AuditEvent struct {
	Seq          int64
	EventID      uuid.UUID
	OrgID        uuid.UUID
	OccurredAt   time.Time
	EventType    string
	ActorUserID  *uuid.UUID
	ActorDisplay string
	ActorKind    string
	SourceIp     *netip.Addr
	TargetType   *string
	TargetID     *string
	Reason       *string
	Result       string
	Details      json.RawMessage
	BeforeState  json.RawMessage
	AfterState   json.RawMessage
	RequestID    *string
	TraceID      *string
}

type LocalCredential struct {
	UserID               uuid.UUID
	PasswordHash         string
	PasswordChangedAt    time.Time
	MustChangePassword   bool
	FailedAttempts       int32
	LockedUntil          *time.Time
	TotpSecretEnc        []byte
	TotpPendingSecretEnc []byte
	TotpEnabled          bool
	TotpLastStep         int64
}

type NotificationOutbox struct {
	ID          int64
	OrgID       uuid.UUID
	EventType   string
	Severity    string
	Payload     json.RawMessage
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type OidcAuthRequest struct {
	State        string
	Provider     string
	Nonce        string
	CodeVerifier string
	ReturnTo     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type OidcGroupMapping struct {
	OrgID     uuid.UUID
	Provider  string
	GroupID   string
	Role      string
	CreatedAt time.Time
}

type Organization struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
}

type Session struct {
	ID         []byte
	UserID     uuid.UUID
	AuthMethod string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
	SourceIp   *netip.Addr
	UserAgent  *string
	RevokedAt  *time.Time
}

type User struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Kind         string
	Username     string
	DisplayName  string
	Email        *string
	OidcProvider *string
	OidcIssuer   *string
	OidcSubject  *string
	Disabled     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  *time.Time
}

type UserRole struct {
	UserID    uuid.UUID
	Role      string
	Source    string
	GrantedAt time.Time
	GrantedBy *uuid.UUID
}
