// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Agent struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	Hostname            string
	Status              string
	StatusReason        *string
	StatusChangedAt     time.Time
	StatusChangedBy     *uuid.UUID
	EnrolledAt          time.Time
	ApprovedAt          *time.Time
	AgentVersion        string
	ProtocolVersion     string
	OsRelease           *string
	Architecture        *string
	CertSerial          *string
	CertFingerprint     *string
	CertNotAfter        *time.Time
	LastSeenAt          *time.Time
	LastLatencyMs       *int32
	DockerReachable     *bool
	DockerVersion       *string
	HealthError         *string
	RegistrationTokenID *uuid.UUID
}

type AgentCertificate struct {
	Serial      string
	AgentID     uuid.UUID
	Fingerprint string
	NotBefore   time.Time
	NotAfter    time.Time
	IssuedAt    time.Time
	RevokedAt   *time.Time
}

type AgentCommand struct {
	CommandID string
	AgentID   uuid.UUID
	Kind      string
	State     string
	Error     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AgentRegistrationToken struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	TokenHash   []byte
	Prefix      string
	Description string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UsedAt      *time.Time
	UsedByAgent *uuid.UUID
	RevokedAt   *time.Time
}

type AgentRepositoryAccess struct {
	AgentID      uuid.UUID
	RepositoryID uuid.UUID
	Username     string
	Hostname     string
	ConfiguredAt time.Time
}

type AgentSession struct {
	AgentID         uuid.UUID
	SessionID       string
	GatewayInstance string
	RemoteAddr      *string
	ConnectedAt     time.Time
	LastHeartbeatAt time.Time
}

type ApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  []byte
	Prefix     string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type Application struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	AgentID          uuid.UUID
	Key              string
	Kind             string
	Name             string
	DisplayName      *string
	Owner            *string
	Environment      *string
	Criticality      *string
	ManualContainers []string
	FirstSeenAt      time.Time
	LastSeenAt       time.Time
	MissingSince     *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ApplicationBackupSetting struct {
	ApplicationID      uuid.UUID
	RepositoryID       *uuid.UUID
	ConsistencyMode    *string
	MaxQuiesceSeconds  int32
	PreHooks           json.RawMessage
	PostHooks          json.RawMessage
	OptionalComponents []string
	ExcludedComponents []string
	UpdatedBy          *uuid.UUID
	UpdatedAt          time.Time
}

type AuditEvent struct {
	Seq          int64
	EventID      uuid.UUID
	OrgID        uuid.UUID
	OccurredAt   time.Time
	EventType    string
	ActorUserID  *uuid.UUID
	ActorDisplay string
	ActorKind    string
	SourceIp     *netip.Addr
	TargetType   *string
	TargetID     *string
	Reason       *string
	Result       string
	Details      json.RawMessage
	BeforeState  json.RawMessage
	AfterState   json.RawMessage
	RequestID    *string
	TraceID      *string
}

type EscrowRecipient struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	PublicKey string
	CreatedBy *uuid.UUID
	CreatedAt time.Time
	RemovedAt *time.Time
}

type HostSetting struct {
	AgentID              uuid.UUID
	MaxConcurrentJobs    int32
	BackupWindowStart    *int32
	BackupWindowEnd      *int32
	BackupWindowTimezone string
	UpdatedBy            *uuid.UUID
	UpdatedAt            time.Time
}

type InventorySnapshot struct {
	AgentID       uuid.UUID
	OrgID         uuid.UUID
	SchemaVersion int32
	CollectedAt   time.Time
	ReceivedAt    time.Time
	Data          json.RawMessage
}

type LocalCredential struct {
	UserID               uuid.UUID
	PasswordHash         string
	PasswordChangedAt    time.Time
	MustChangePassword   bool
	FailedAttempts       int32
	LockedUntil          *time.Time
	TotpSecretEnc        []byte
	TotpPendingSecretEnc []byte
	TotpEnabled          bool
	TotpLastStep         int64
}

type NotificationOutbox struct {
	ID             int64
	OrgID          uuid.UUID
	EventType      string
	Severity       string
	Payload        json.RawMessage
	CreatedAt      time.Time
	DeliveredAt    *time.Time
	TargetType     *string
	TargetID       *string
	Message        string
	AcknowledgedAt *time.Time
	AcknowledgedBy *uuid.UUID
}

type OidcAuthRequest struct {
	State        string
	Provider     string
	Nonce        string
	CodeVerifier string
	ReturnTo     string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type OidcGroupMapping struct {
	OrgID     uuid.UUID
	Provider  string
	GroupID   string
	Role      string
	CreatedAt time.Time
}

type Organization struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
}

type PkiAuthority struct {
	Name        string
	OrgID       uuid.UUID
	CertDer     []byte
	KeyEnc      []byte
	Fingerprint string
	CreatedAt   time.Time
}

type RecoveryPoint struct {
	ID                  string
	OrgID               uuid.UUID
	RepositoryID        uuid.UUID
	ApplicationID       uuid.UUID
	ApplicationName     string
	AgentID             uuid.UUID
	Hostname            string
	State               string
	Status              *string
	Verification        string
	ConsistencyMode     string
	ConsistencyPoint    *time.Time
	CrashConsistentOnly bool
	Trigger             string
	RequestedBy         *uuid.UUID
	WorkflowID          string
	RunID               string
	SizeBytes           int64
	ComponentCount      int32
	Manifest            json.RawMessage
	ManifestSnapshotID  *string
	Error               *string
	CreatedAt           time.Time
	CommittedAt         *time.Time
	UpdatedAt           time.Time
}

type Repository struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	Name               string
	Description        string
	Backend            string
	ManagementUrl      string
	ServerUrl          string
	InternalServerUrl  string
	CertSha256         string
	KopiaRepositoryID  *string
	Splitter           *string
	Status             string
	IsDefault          bool
	EscrowPackage      []byte
	EscrowRecipientIds []uuid.UUID
	EscrowConfirmHash  []byte
	EscrowGeneratedAt  *time.Time
	EscrowConfirmedAt  *time.Time
	EscrowConfirmedBy  *uuid.UUID
	LastReindexAt      *time.Time
	CreatedBy          *uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Session struct {
	ID         []byte
	UserID     uuid.UUID
	AuthMethod string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
	SourceIp   *netip.Addr
	UserAgent  *string
	RevokedAt  *time.Time
}

type User struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	Kind         string
	Username     string
	DisplayName  string
	Email        *string
	OidcProvider *string
	OidcIssuer   *string
	OidcSubject  *string
	Disabled     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastLoginAt  *time.Time
}

type UserRole struct {
	UserID    uuid.UUID
	Role      string
	Source    string
	GrantedAt time.Time
	GrantedBy *uuid.UUID
}
