// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many

WITH due AS (
    SELECT dd.id FROM notification_deliveries dd
    WHERE dd.state = 'pending' AND dd.next_attempt_at <= now()
    ORDER BY dd.next_attempt_at, dd.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE notification_deliveries d
SET attempts = d.attempts + 1, next_attempt_at = now() + make_interval(secs => $1::double precision)
FROM due WHERE d.id = due.id
RETURNING d.id, d.notification_id, d.channel_id, d.attempts
`

type ClaimDueDeliveriesParams struct {
	LeaseSeconds float64
	Batch        int32
}

type ClaimDueDeliveriesRow struct {
	ID             int64
	NotificationID int64
	ChannelID      uuid.UUID
	Attempts       int32
}

// ---- Deliveries ----------------------------------------------------------------
// Claims due deliveries with a lease: attempts is incremented and the next
// attempt pushed past the lease, so a crashed sender's work is retried and
// concurrent dispatchers never claim the same row.
func (q *Queries) ClaimDueDeliveries(ctx context.Context, arg ClaimDueDeliveriesParams) ([]ClaimDueDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDueDeliveries, arg.LeaseSeconds, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueDeliveriesRow
	for rows.Next() {
		var i ClaimDueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ChannelID,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimUndeliveredNotifications = `-- name: ClaimUndeliveredNotifications :many

SELECT id, org_id, event_type, severity, payload, created_at, delivered_at, target_type, target_id, message, acknowledged_at, acknowledged_by FROM notification_outbox WHERE delivered_at IS NULL
ORDER BY id LIMIT $1
FOR UPDATE SKIP LOCKED
`

// ---- Fan-out -------------------------------------------------------------------
// Run inside a transaction: the claimed rows stay locked until it commits, and
// other dispatchers skip them.
func (q *Queries) ClaimUndeliveredNotifications(ctx context.Context, limit int32) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, claimUndeliveredNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EventType,
			&i.Severity,
			&i.Payload,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.TargetType,
			&i.TargetID,
			&i.Message,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAgentOfflineAlerted = `-- name: ClearAgentOfflineAlerted :execrows
UPDATE agents SET offline_alerted_at = NULL WHERE id = $1 AND offline_alerted_at IS NOT NULL
`

func (q *Queries) ClearAgentOfflineAlerted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearAgentOfflineAlerted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one


INSERT INTO notification_channels (id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by, created_at, updated_at, last_delivery_at, last_error
`

type CreateNotificationChannelParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Enabled     bool
	Config      json.RawMessage
	SecretEnc   []byte
	Events      []string
	MinSeverity string
	CreatedBy   *uuid.UUID
}

// SPDX-License-Identifier: Apache-2.0
// ---- Channels ----------------------------------------------------------------
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Enabled,
		arg.Config,
		arg.SecretEnc,
		arg.Events,
		arg.MinSeverity,
		arg.CreatedBy,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Config,
		&i.SecretEnc,
		&i.Events,
		&i.MinSeverity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryAt,
		&i.LastError,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels WHERE id = $1 AND org_id = $2
`

type DeleteNotificationChannelParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by, created_at, updated_at, last_delivery_at, last_error FROM notification_channels WHERE id = $1 AND org_id = $2
`

type GetNotificationChannelParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.OrgID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Config,
		&i.SecretEnc,
		&i.Events,
		&i.MinSeverity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryAt,
		&i.LastError,
	)
	return i, err
}

const getNotificationChannelByID = `-- name: GetNotificationChannelByID :one
SELECT id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by, created_at, updated_at, last_delivery_at, last_error FROM notification_channels WHERE id = $1
`

func (q *Queries) GetNotificationChannelByID(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Config,
		&i.SecretEnc,
		&i.Events,
		&i.MinSeverity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryAt,
		&i.LastError,
	)
	return i, err
}

const getOutboxNotification = `-- name: GetOutboxNotification :one
SELECT id, org_id, event_type, severity, payload, created_at, delivered_at, target_type, target_id, message, acknowledged_at, acknowledged_by FROM notification_outbox WHERE id = $1
`

func (q *Queries) GetOutboxNotification(ctx context.Context, id int64) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, getOutboxNotification, id)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventType,
		&i.Severity,
		&i.Payload,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.TargetType,
		&i.TargetID,
		&i.Message,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
	)
	return i, err
}

const getPlatformSetting = `-- name: GetPlatformSetting :one

SELECT org_id, key, value, secret_enc, updated_by, updated_at FROM platform_settings WHERE org_id = $1 AND key = $2
`

type GetPlatformSettingParams struct {
	OrgID uuid.UUID
	Key   string
}

// ---- Platform settings --------------------------------------------------------
func (q *Queries) GetPlatformSetting(ctx context.Context, arg GetPlatformSettingParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getPlatformSetting, arg.OrgID, arg.Key)
	var i PlatformSetting
	err := row.Scan(
		&i.OrgID,
		&i.Key,
		&i.Value,
		&i.SecretEnc,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :exec
INSERT INTO notification_deliveries (notification_id, channel_id) VALUES ($1, $2)
ON CONFLICT (notification_id, channel_id) DO NOTHING
`

type InsertNotificationDeliveryParams struct {
	NotificationID int64
	ChannelID      uuid.UUID
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationDelivery, arg.NotificationID, arg.ChannelID)
	return err
}

const listActiveAgentPresence = `-- name: ListActiveAgentPresence :many

SELECT id, org_id, hostname, last_seen_at, offline_alerted_at,
       GREATEST(COALESCE(last_seen_at, status_changed_at), status_changed_at)::timestamptz AS last_activity
FROM agents WHERE status = 'active'
`

type ListActiveAgentPresenceRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Hostname         string
	LastSeenAt       *time.Time
	OfflineAlertedAt *time.Time
	LastActivity     time.Time
}

// ---- Agent presence -----------------------------------------------------------
// last_activity: the latest sign of life (heartbeat, health report) or the
// last status change (an agent just approved or resumed is not "offline").
func (q *Queries) ListActiveAgentPresence(ctx context.Context) ([]ListActiveAgentPresenceRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgentPresence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAgentPresenceRow
	for rows.Next() {
		var i ListActiveAgentPresenceRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Hostname,
			&i.LastSeenAt,
			&i.OfflineAlertedAt,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelDeliveries = `-- name: ListChannelDeliveries :many
SELECT d.id, d.notification_id, d.channel_id, d.state, d.attempts, d.next_attempt_at, d.last_error, d.sent_at, d.created_at,
       o.event_type, o.severity, o.message
FROM notification_deliveries d
JOIN notification_outbox o ON o.id = d.notification_id
WHERE d.channel_id = $1
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListChannelDeliveriesParams struct {
	ChannelID uuid.UUID
	Limit     int32
}

type ListChannelDeliveriesRow struct {
	ID             int64
	NotificationID int64
	ChannelID      uuid.UUID
	State          string
	Attempts       int32
	NextAttemptAt  time.Time
	LastError      *string
	SentAt         *time.Time
	CreatedAt      time.Time
	EventType      string
	Severity       string
	Message        string
}

func (q *Queries) ListChannelDeliveries(ctx context.Context, arg ListChannelDeliveriesParams) ([]ListChannelDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listChannelDeliveries, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelDeliveriesRow
	for rows.Next() {
		var i ListChannelDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ChannelID,
			&i.State,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
			&i.EventType,
			&i.Severity,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledNotificationChannels = `-- name: ListEnabledNotificationChannels :many
SELECT id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by, created_at, updated_at, last_delivery_at, last_error FROM notification_channels WHERE enabled ORDER BY org_id, id
`

func (q *Queries) ListEnabledNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.Config,
			&i.SecretEnc,
			&i.Events,
			&i.MinSeverity,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastDeliveryAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by, created_at, updated_at, last_delivery_at, last_error FROM notification_channels WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListNotificationChannels(ctx context.Context, orgID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.Config,
			&i.SecretEnc,
			&i.Events,
			&i.MinSeverity,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastDeliveryAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentOfflineAlerted = `-- name: MarkAgentOfflineAlerted :execrows
UPDATE agents SET offline_alerted_at = now() WHERE id = $1 AND offline_alerted_at IS NULL
`

// Conditional: exactly one dispatcher raises agent.offline per outage.
func (q *Queries) MarkAgentOfflineAlerted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAgentOfflineAlerted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE notification_deliveries SET state = 'failed', last_error = $2 WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID        int64
	LastError *string
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.LastError)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE notification_deliveries SET last_error = $2, next_attempt_at = $3 WHERE id = $1 AND state = 'pending'
`

type MarkDeliveryRetryParams struct {
	ID            int64
	LastError     *string
	NextAttemptAt time.Time
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, markDeliveryRetry, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE notification_deliveries SET state = 'sent', sent_at = now(), last_error = NULL WHERE id = $1
`

func (q *Queries) MarkDeliverySent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDeliverySent, id)
	return err
}

const markNotificationsFannedOut = `-- name: MarkNotificationsFannedOut :exec
UPDATE notification_outbox SET delivered_at = now() WHERE id = ANY($1::bigint[]) AND delivered_at IS NULL
`

func (q *Queries) MarkNotificationsFannedOut(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markNotificationsFannedOut, ids)
	return err
}

const recordNotificationChannelResult = `-- name: RecordNotificationChannelResult :exec
UPDATE notification_channels
SET last_delivery_at = CASE WHEN $1::boolean THEN now() ELSE last_delivery_at END,
    last_error = $2
WHERE id = $3
`

type RecordNotificationChannelResultParams struct {
	Ok        bool
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) RecordNotificationChannelResult(ctx context.Context, arg RecordNotificationChannelResultParams) error {
	_, err := q.db.Exec(ctx, recordNotificationChannelResult, arg.Ok, arg.LastError, arg.ID)
	return err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels SET name = $1, enabled = $2, config = $3, events = $4,
    min_severity = $5,
    secret_enc = CASE WHEN $6::boolean THEN $7::bytea ELSE secret_enc END,
    updated_at = now()
WHERE id = $8 AND org_id = $9
RETURNING id, org_id, name, kind, enabled, config, secret_enc, events, min_severity, created_by, created_at, updated_at, last_delivery_at, last_error
`

type UpdateNotificationChannelParams struct {
	Name        string
	Enabled     bool
	Config      json.RawMessage
	Events      []string
	MinSeverity string
	SetSecret   bool
	SecretEnc   []byte
	ID          uuid.UUID
	OrgID       uuid.UUID
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.Name,
		arg.Enabled,
		arg.Config,
		arg.Events,
		arg.MinSeverity,
		arg.SetSecret,
		arg.SecretEnc,
		arg.ID,
		arg.OrgID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Config,
		&i.SecretEnc,
		&i.Events,
		&i.MinSeverity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryAt,
		&i.LastError,
	)
	return i, err
}

const upsertPlatformSetting = `-- name: UpsertPlatformSetting :one
INSERT INTO platform_settings (org_id, key, value, secret_enc, updated_by)
VALUES ($1, $2, $3, $4::bytea, $5)
ON CONFLICT (org_id, key) DO UPDATE SET value = EXCLUDED.value,
    secret_enc = CASE WHEN $6::boolean THEN EXCLUDED.secret_enc ELSE platform_settings.secret_enc END,
    updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING org_id, key, value, secret_enc, updated_by, updated_at
`

type UpsertPlatformSettingParams struct {
	OrgID     uuid.UUID
	Key       string
	Value     json.RawMessage
	SecretEnc []byte
	UpdatedBy *uuid.UUID
	SetSecret bool
}

func (q *Queries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, upsertPlatformSetting,
		arg.OrgID,
		arg.Key,
		arg.Value,
		arg.SecretEnc,
		arg.UpdatedBy,
		arg.SetSecret,
	)
	var i PlatformSetting
	err := row.Scan(
		&i.OrgID,
		&i.Key,
		&i.Value,
		&i.SecretEnc,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
