// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const abandonRunningPlatformBackups = `-- name: AbandonRunningPlatformBackups :execrows
UPDATE platform_backups SET state = 'failed', finished_at = now(),
    error = 'abandoned: the run did not finish (worker or server restarted)'
WHERE org_id = $1 AND state = 'running' AND started_at < $2
`

type AbandonRunningPlatformBackupsParams struct {
	OrgID     uuid.UUID
	StartedAt time.Time
}

func (q *Queries) AbandonRunningPlatformBackups(ctx context.Context, arg AbandonRunningPlatformBackupsParams) (int64, error) {
	result, err := q.db.Exec(ctx, abandonRunningPlatformBackups, arg.OrgID, arg.StartedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearSystemRepository = `-- name: ClearSystemRepository :exec
UPDATE repositories SET is_system = false, updated_at = now() WHERE org_id = $1 AND is_system
`

func (q *Queries) ClearSystemRepository(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSystemRepository, orgID)
	return err
}

const createPlatformBackup = `-- name: CreatePlatformBackup :one

INSERT INTO platform_backups (id, org_id, trigger, requested_by, workflow_id, run_id, repository_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, state, trigger, requested_by, workflow_id, run_id, started_at, finished_at, size_bytes, sha256, file_name, snapshot_id, repository_id, bundle_path, error, manifest
`

type CreatePlatformBackupParams struct {
	ID           string
	OrgID        uuid.UUID
	Trigger      string
	RequestedBy  *uuid.UUID
	WorkflowID   *string
	RunID        *string
	RepositoryID *uuid.UUID
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreatePlatformBackup(ctx context.Context, arg CreatePlatformBackupParams) (PlatformBackup, error) {
	row := q.db.QueryRow(ctx, createPlatformBackup,
		arg.ID,
		arg.OrgID,
		arg.Trigger,
		arg.RequestedBy,
		arg.WorkflowID,
		arg.RunID,
		arg.RepositoryID,
	)
	var i PlatformBackup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.State,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SizeBytes,
		&i.Sha256,
		&i.FileName,
		&i.SnapshotID,
		&i.RepositoryID,
		&i.BundlePath,
		&i.Error,
		&i.Manifest,
	)
	return i, err
}

const finishPlatformBackup = `-- name: FinishPlatformBackup :one
UPDATE platform_backups SET state = $2, finished_at = now(), size_bytes = $3, sha256 = $4, file_name = $5,
    snapshot_id = $6, repository_id = coalesce($7, repository_id), bundle_path = $8, error = $9
WHERE id = $1 AND state = 'running'
RETURNING id, org_id, state, trigger, requested_by, workflow_id, run_id, started_at, finished_at, size_bytes, sha256, file_name, snapshot_id, repository_id, bundle_path, error, manifest
`

type FinishPlatformBackupParams struct {
	ID           string
	State        string
	SizeBytes    int64
	Sha256       *string
	FileName     *string
	SnapshotID   *string
	RepositoryID *uuid.UUID
	BundlePath   *string
	Error        *string
}

func (q *Queries) FinishPlatformBackup(ctx context.Context, arg FinishPlatformBackupParams) (PlatformBackup, error) {
	row := q.db.QueryRow(ctx, finishPlatformBackup,
		arg.ID,
		arg.State,
		arg.SizeBytes,
		arg.Sha256,
		arg.FileName,
		arg.SnapshotID,
		arg.RepositoryID,
		arg.BundlePath,
		arg.Error,
	)
	var i PlatformBackup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.State,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SizeBytes,
		&i.Sha256,
		&i.FileName,
		&i.SnapshotID,
		&i.RepositoryID,
		&i.BundlePath,
		&i.Error,
		&i.Manifest,
	)
	return i, err
}

const getPlatformBackup = `-- name: GetPlatformBackup :one
SELECT id, org_id, state, trigger, requested_by, workflow_id, run_id, started_at, finished_at, size_bytes, sha256, file_name, snapshot_id, repository_id, bundle_path, error, manifest FROM platform_backups WHERE id = $1
`

func (q *Queries) GetPlatformBackup(ctx context.Context, id string) (PlatformBackup, error) {
	row := q.db.QueryRow(ctx, getPlatformBackup, id)
	var i PlatformBackup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.State,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SizeBytes,
		&i.Sha256,
		&i.FileName,
		&i.SnapshotID,
		&i.RepositoryID,
		&i.BundlePath,
		&i.Error,
		&i.Manifest,
	)
	return i, err
}

const getRunningPlatformBackup = `-- name: GetRunningPlatformBackup :one
SELECT id, org_id, state, trigger, requested_by, workflow_id, run_id, started_at, finished_at, size_bytes, sha256, file_name, snapshot_id, repository_id, bundle_path, error, manifest FROM platform_backups WHERE org_id = $1 AND state = 'running' ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetRunningPlatformBackup(ctx context.Context, orgID uuid.UUID) (PlatformBackup, error) {
	row := q.db.QueryRow(ctx, getRunningPlatformBackup, orgID)
	var i PlatformBackup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.State,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SizeBytes,
		&i.Sha256,
		&i.FileName,
		&i.SnapshotID,
		&i.RepositoryID,
		&i.BundlePath,
		&i.Error,
		&i.Manifest,
	)
	return i, err
}

const getSystemRepository = `-- name: GetSystemRepository :one
SELECT id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system FROM repositories WHERE org_id = $1 AND is_system AND status <> 'retired'
`

func (q *Queries) GetSystemRepository(ctx context.Context, orgID uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getSystemRepository, orgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const listPlatformBackups = `-- name: ListPlatformBackups :many
SELECT id, org_id, state, trigger, requested_by, workflow_id, run_id, started_at, finished_at, size_bytes, sha256, file_name, snapshot_id, repository_id, bundle_path, error, manifest FROM platform_backups WHERE org_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListPlatformBackupsParams struct {
	OrgID uuid.UUID
	Limit int32
}

func (q *Queries) ListPlatformBackups(ctx context.Context, arg ListPlatformBackupsParams) ([]PlatformBackup, error) {
	rows, err := q.db.Query(ctx, listPlatformBackups, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformBackup
	for rows.Next() {
		var i PlatformBackup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.State,
			&i.Trigger,
			&i.RequestedBy,
			&i.WorkflowID,
			&i.RunID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SizeBytes,
			&i.Sha256,
			&i.FileName,
			&i.SnapshotID,
			&i.RepositoryID,
			&i.BundlePath,
			&i.Error,
			&i.Manifest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlatformBackupManifest = `-- name: SetPlatformBackupManifest :exec
UPDATE platform_backups SET manifest = $2 WHERE id = $1
`

type SetPlatformBackupManifestParams struct {
	ID       string
	Manifest json.RawMessage
}

func (q *Queries) SetPlatformBackupManifest(ctx context.Context, arg SetPlatformBackupManifestParams) error {
	_, err := q.db.Exec(ctx, setPlatformBackupManifest, arg.ID, arg.Manifest)
	return err
}

const setSystemRepository = `-- name: SetSystemRepository :one
UPDATE repositories SET is_system = true, updated_at = now() WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

type SetSystemRepositoryParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) SetSystemRepository(ctx context.Context, arg SetSystemRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, setSystemRepository, arg.ID, arg.OrgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}
