// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelRecoveryPointDeletion = `-- name: CancelRecoveryPointDeletion :one
UPDATE recovery_points SET delete_after = NULL, delete_reason = NULL, delete_requested_by = NULL, updated_at = now()
WHERE id = $1 AND org_id = $2 AND state IN ('committed', 'missing') AND delete_after IS NOT NULL
RETURNING id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at, delete_after, delete_reason, delete_requested_by, deleted_at, verified_at, verification_details
`

type CancelRecoveryPointDeletionParams struct {
	ID    string
	OrgID uuid.UUID
}

func (q *Queries) CancelRecoveryPointDeletion(ctx context.Context, arg CancelRecoveryPointDeletionParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, cancelRecoveryPointDeletion, arg.ID, arg.OrgID)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.DeleteRequestedBy,
		&i.DeletedAt,
		&i.VerifiedAt,
		&i.VerificationDetails,
	)
	return i, err
}

const cancelRepositoryDeletion = `-- name: CancelRepositoryDeletion :one
UPDATE repositories SET status = CASE WHEN escrow_confirmed_at IS NULL THEN 'awaiting_escrow' ELSE 'ready' END,
    delete_after = NULL, delete_reason = NULL, updated_at = now()
WHERE id = $1 AND org_id = $2 AND status = 'pending_deletion'
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

type CancelRepositoryDeletionParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) CancelRepositoryDeletion(ctx context.Context, arg CancelRepositoryDeletionParams) (Repository, error) {
	row := q.db.QueryRow(ctx, cancelRepositoryDeletion, arg.ID, arg.OrgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const completeEscrowDrill = `-- name: CompleteEscrowDrill :one
UPDATE escrow_drills SET completed_at = now(), completed_by = $3 WHERE id = $1 AND org_id = $2 AND completed_at IS NULL
RETURNING id, org_id, package, code_hash, recipient_ids, created_by, created_at, completed_at, completed_by
`

type CompleteEscrowDrillParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	CompletedBy *uuid.UUID
}

func (q *Queries) CompleteEscrowDrill(ctx context.Context, arg CompleteEscrowDrillParams) (EscrowDrill, error) {
	row := q.db.QueryRow(ctx, completeEscrowDrill, arg.ID, arg.OrgID, arg.CompletedBy)
	var i EscrowDrill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Package,
		&i.CodeHash,
		&i.RecipientIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const createEscrowDrill = `-- name: CreateEscrowDrill :one
INSERT INTO escrow_drills (org_id, package, code_hash, recipient_ids, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, package, code_hash, recipient_ids, created_by, created_at, completed_at, completed_by
`

type CreateEscrowDrillParams struct {
	OrgID        uuid.UUID
	Package      []byte
	CodeHash     []byte
	RecipientIds []uuid.UUID
	CreatedBy    *uuid.UUID
}

func (q *Queries) CreateEscrowDrill(ctx context.Context, arg CreateEscrowDrillParams) (EscrowDrill, error) {
	row := q.db.QueryRow(ctx, createEscrowDrill,
		arg.OrgID,
		arg.Package,
		arg.CodeHash,
		arg.RecipientIds,
		arg.CreatedBy,
	)
	var i EscrowDrill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Package,
		&i.CodeHash,
		&i.RecipientIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO protection_policies (org_id, name, description, schedule, timezone, enabled, consistency_mode, repository_id,
    keep_last, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, org_id, name, description, schedule, timezone, enabled, consistency_mode, repository_id, keep_last, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, created_by, created_at, updated_at
`

type CreatePolicyParams struct {
	OrgID           uuid.UUID
	Name            string
	Description     string
	Schedule        string
	Timezone        string
	Enabled         bool
	ConsistencyMode *string
	RepositoryID    *uuid.UUID
	KeepLast        int32
	KeepHourly      int32
	KeepDaily       int32
	KeepWeekly      int32
	KeepMonthly     int32
	KeepYearly      int32
	CreatedBy       *uuid.UUID
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (ProtectionPolicy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Schedule,
		arg.Timezone,
		arg.Enabled,
		arg.ConsistencyMode,
		arg.RepositoryID,
		arg.KeepLast,
		arg.KeepHourly,
		arg.KeepDaily,
		arg.KeepWeekly,
		arg.KeepMonthly,
		arg.KeepYearly,
		arg.CreatedBy,
	)
	var i ProtectionPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Schedule,
		&i.Timezone,
		&i.Enabled,
		&i.ConsistencyMode,
		&i.RepositoryID,
		&i.KeepLast,
		&i.KeepHourly,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.KeepYearly,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContract = `-- name: DeleteContract :execrows
DELETE FROM recovery_contracts WHERE application_id = $1
`

func (q *Queries) DeleteContract(ctx context.Context, applicationID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContract, applicationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePolicy = `-- name: DeletePolicy :execrows
DELETE FROM protection_policies WHERE id = $1 AND org_id = $2
`

type DeletePolicyParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeletePolicy(ctx context.Context, arg DeletePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePolicy, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContract = `-- name: GetContract :one
SELECT application_id, max_rpo_minutes, required_components, state, state_reasons, evaluated_at, violated_since, updated_by, updated_at FROM recovery_contracts WHERE application_id = $1
`

func (q *Queries) GetContract(ctx context.Context, applicationID uuid.UUID) (RecoveryContract, error) {
	row := q.db.QueryRow(ctx, getContract, applicationID)
	var i RecoveryContract
	err := row.Scan(
		&i.ApplicationID,
		&i.MaxRpoMinutes,
		&i.RequiredComponents,
		&i.State,
		&i.StateReasons,
		&i.EvaluatedAt,
		&i.ViolatedSince,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getEscrowDrill = `-- name: GetEscrowDrill :one
SELECT id, org_id, package, code_hash, recipient_ids, created_by, created_at, completed_at, completed_by FROM escrow_drills WHERE id = $1 AND org_id = $2
`

type GetEscrowDrillParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetEscrowDrill(ctx context.Context, arg GetEscrowDrillParams) (EscrowDrill, error) {
	row := q.db.QueryRow(ctx, getEscrowDrill, arg.ID, arg.OrgID)
	var i EscrowDrill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Package,
		&i.CodeHash,
		&i.RecipientIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, org_id, name, description, schedule, timezone, enabled, consistency_mode, repository_id, keep_last, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, created_by, created_at, updated_at FROM protection_policies WHERE id = $1 AND org_id = $2
`

type GetPolicyParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetPolicy(ctx context.Context, arg GetPolicyParams) (ProtectionPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicy, arg.ID, arg.OrgID)
	var i ProtectionPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Schedule,
		&i.Timezone,
		&i.Enabled,
		&i.ConsistencyMode,
		&i.RepositoryID,
		&i.KeepLast,
		&i.KeepHourly,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.KeepYearly,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastCompletedEscrowDrill = `-- name: LastCompletedEscrowDrill :one
SELECT id, org_id, package, code_hash, recipient_ids, created_by, created_at, completed_at, completed_by FROM escrow_drills WHERE org_id = $1 AND completed_at IS NOT NULL ORDER BY completed_at DESC LIMIT 1
`

func (q *Queries) LastCompletedEscrowDrill(ctx context.Context, orgID uuid.UUID) (EscrowDrill, error) {
	row := q.db.QueryRow(ctx, lastCompletedEscrowDrill, orgID)
	var i EscrowDrill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Package,
		&i.CodeHash,
		&i.RecipientIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const listApplicationsForPolicy = `-- name: ListApplicationsForPolicy :many
SELECT a.id, a.name, a.agent_id FROM applications a WHERE a.policy_id = $1 ORDER BY a.name
`

type ListApplicationsForPolicyRow struct {
	ID      uuid.UUID
	Name    string
	AgentID uuid.UUID
}

func (q *Queries) ListApplicationsForPolicy(ctx context.Context, policyID *uuid.UUID) ([]ListApplicationsForPolicyRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsForPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsForPolicyRow
	for rows.Next() {
		var i ListApplicationsForPolicyRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AgentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommittedForRetention = `-- name: ListCommittedForRetention :many
SELECT id, application_id, created_at, state, delete_after FROM recovery_points
WHERE org_id = $1 AND application_id = $2 AND state = 'committed'
ORDER BY created_at DESC
`

type ListCommittedForRetentionParams struct {
	OrgID         uuid.UUID
	ApplicationID uuid.UUID
}

type ListCommittedForRetentionRow struct {
	ID            string
	ApplicationID uuid.UUID
	CreatedAt     time.Time
	State         string
	DeleteAfter   *time.Time
}

func (q *Queries) ListCommittedForRetention(ctx context.Context, arg ListCommittedForRetentionParams) ([]ListCommittedForRetentionRow, error) {
	rows, err := q.db.Query(ctx, listCommittedForRetention, arg.OrgID, arg.ApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommittedForRetentionRow
	for rows.Next() {
		var i ListCommittedForRetentionRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.State,
			&i.DeleteAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContracts = `-- name: ListContracts :many
SELECT c.application_id, c.max_rpo_minutes, c.required_components, c.state, c.state_reasons, c.evaluated_at, c.violated_since, c.updated_by, c.updated_at, a.name AS application_name, a.agent_id FROM recovery_contracts c
JOIN applications a ON a.id = c.application_id WHERE a.org_id = $1 ORDER BY a.name
`

type ListContractsRow struct {
	ApplicationID      uuid.UUID
	MaxRpoMinutes      *int32
	RequiredComponents []string
	State              string
	StateReasons       []string
	EvaluatedAt        *time.Time
	ViolatedSince      *time.Time
	UpdatedBy          *uuid.UUID
	UpdatedAt          time.Time
	ApplicationName    string
	AgentID            uuid.UUID
}

func (q *Queries) ListContracts(ctx context.Context, orgID uuid.UUID) ([]ListContractsRow, error) {
	rows, err := q.db.Query(ctx, listContracts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsRow
	for rows.Next() {
		var i ListContractsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.MaxRpoMinutes,
			&i.RequiredComponents,
			&i.State,
			&i.StateReasons,
			&i.EvaluatedAt,
			&i.ViolatedSince,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.ApplicationName,
			&i.AgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeletions = `-- name: ListDueDeletions :many
SELECT id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at, delete_after, delete_reason, delete_requested_by, deleted_at, verified_at, verification_details FROM recovery_points WHERE org_id = $1 AND delete_after IS NOT NULL AND delete_after <= now()
  AND state IN ('committed', 'missing', 'deleting')
ORDER BY delete_after LIMIT $2
`

type ListDueDeletionsParams struct {
	OrgID uuid.UUID
	Limit int32
}

func (q *Queries) ListDueDeletions(ctx context.Context, arg ListDueDeletionsParams) ([]RecoveryPoint, error) {
	rows, err := q.db.Query(ctx, listDueDeletions, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryPoint
	for rows.Next() {
		var i RecoveryPoint
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RepositoryID,
			&i.ApplicationID,
			&i.ApplicationName,
			&i.AgentID,
			&i.Hostname,
			&i.State,
			&i.Status,
			&i.Verification,
			&i.ConsistencyMode,
			&i.ConsistencyPoint,
			&i.CrashConsistentOnly,
			&i.Trigger,
			&i.RequestedBy,
			&i.WorkflowID,
			&i.RunID,
			&i.SizeBytes,
			&i.ComponentCount,
			&i.Manifest,
			&i.ManifestSnapshotID,
			&i.Error,
			&i.CreatedAt,
			&i.CommittedAt,
			&i.UpdatedAt,
			&i.DeleteAfter,
			&i.DeleteReason,
			&i.DeleteRequestedBy,
			&i.DeletedAt,
			&i.VerifiedAt,
			&i.VerificationDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscrowDrills = `-- name: ListEscrowDrills :many
SELECT id, org_id, package, code_hash, recipient_ids, created_by, created_at, completed_at, completed_by FROM escrow_drills WHERE org_id = $1 ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListEscrowDrills(ctx context.Context, orgID uuid.UUID) ([]EscrowDrill, error) {
	rows, err := q.db.Query(ctx, listEscrowDrills, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EscrowDrill
	for rows.Next() {
		var i EscrowDrill
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Package,
			&i.CodeHash,
			&i.RecipientIds,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.CompletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many

SELECT p.id, p.org_id, p.name, p.description, p.schedule, p.timezone, p.enabled, p.consistency_mode, p.repository_id, p.keep_last, p.keep_hourly, p.keep_daily, p.keep_weekly, p.keep_monthly, p.keep_yearly, p.created_by, p.created_at, p.updated_at, (SELECT count(*) FROM applications a WHERE a.policy_id = p.id)::int AS application_count
FROM protection_policies p WHERE p.org_id = $1 ORDER BY p.name
`

type ListPoliciesRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Name             string
	Description      string
	Schedule         string
	Timezone         string
	Enabled          bool
	ConsistencyMode  *string
	RepositoryID     *uuid.UUID
	KeepLast         int32
	KeepHourly       int32
	KeepDaily        int32
	KeepWeekly       int32
	KeepMonthly      int32
	KeepYearly       int32
	CreatedBy        *uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ApplicationCount int32
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) ListPolicies(ctx context.Context, orgID uuid.UUID) ([]ListPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listPolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesRow
	for rows.Next() {
		var i ListPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Schedule,
			&i.Timezone,
			&i.Enabled,
			&i.ConsistencyMode,
			&i.RepositoryID,
			&i.KeepLast,
			&i.KeepHourly,
			&i.KeepDaily,
			&i.KeepWeekly,
			&i.KeepMonthly,
			&i.KeepYearly,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyAssignments = `-- name: ListPolicyAssignments :many
SELECT a.id AS application_id, a.name, a.agent_id, a.policy_id, a.missing_since, p.schedule, p.timezone, p.enabled
FROM applications a JOIN protection_policies p ON p.id = a.policy_id
WHERE a.org_id = $1
`

type ListPolicyAssignmentsRow struct {
	ApplicationID uuid.UUID
	Name          string
	AgentID       uuid.UUID
	PolicyID      *uuid.UUID
	MissingSince  *time.Time
	Schedule      string
	Timezone      string
	Enabled       bool
}

func (q *Queries) ListPolicyAssignments(ctx context.Context, orgID uuid.UUID) ([]ListPolicyAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listPolicyAssignments, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyAssignmentsRow
	for rows.Next() {
		var i ListPolicyAssignmentsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.Name,
			&i.AgentID,
			&i.PolicyID,
			&i.MissingSince,
			&i.Schedule,
			&i.Timezone,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationCandidates = `-- name: ListVerificationCandidates :many
SELECT id, manifest FROM recovery_points
WHERE repository_id = $1 AND state = 'committed' AND manifest IS NOT NULL
ORDER BY verified_at NULLS FIRST, created_at DESC
LIMIT $2
`

type ListVerificationCandidatesParams struct {
	RepositoryID uuid.UUID
	Limit        int32
}

type ListVerificationCandidatesRow struct {
	ID       string
	Manifest json.RawMessage
}

func (q *Queries) ListVerificationCandidates(ctx context.Context, arg ListVerificationCandidatesParams) ([]ListVerificationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listVerificationCandidates, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationCandidatesRow
	for rows.Next() {
		var i ListVerificationCandidatesRow
		if err := rows.Scan(&i.ID, &i.Manifest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryPointDeleted = `-- name: MarkRecoveryPointDeleted :exec
UPDATE recovery_points SET state = 'deleted', deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkRecoveryPointDeleted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRecoveryPointDeleted, id)
	return err
}

const markRecoveryPointDeleting = `-- name: MarkRecoveryPointDeleting :exec
UPDATE recovery_points SET state = 'deleting', updated_at = now() WHERE id = $1 AND state IN ('committed', 'missing', 'deleting')
`

func (q *Queries) MarkRecoveryPointDeleting(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRecoveryPointDeleting, id)
	return err
}

const regenerateRepositoryEscrow = `-- name: RegenerateRepositoryEscrow :one
UPDATE repositories SET escrow_package = $3, escrow_recipient_ids = $4, escrow_confirm_hash = $5,
    escrow_generated_at = now(), escrow_confirmed_at = NULL, escrow_confirmed_by = NULL, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

type RegenerateRepositoryEscrowParams struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	EscrowPackage      []byte
	EscrowRecipientIds []uuid.UUID
	EscrowConfirmHash  []byte
}

func (q *Queries) RegenerateRepositoryEscrow(ctx context.Context, arg RegenerateRepositoryEscrowParams) (Repository, error) {
	row := q.db.QueryRow(ctx, regenerateRepositoryEscrow,
		arg.ID,
		arg.OrgID,
		arg.EscrowPackage,
		arg.EscrowRecipientIds,
		arg.EscrowConfirmHash,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const retireDueRepositories = `-- name: RetireDueRepositories :many
UPDATE repositories SET status = 'retired', updated_at = now()
WHERE org_id = $1 AND status = 'pending_deletion' AND delete_after <= now()
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

func (q *Queries) RetireDueRepositories(ctx context.Context, orgID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, retireDueRepositories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Backend,
			&i.ManagementUrl,
			&i.ServerUrl,
			&i.InternalServerUrl,
			&i.CertSha256,
			&i.KopiaRepositoryID,
			&i.Splitter,
			&i.Status,
			&i.IsDefault,
			&i.EscrowPackage,
			&i.EscrowRecipientIds,
			&i.EscrowConfirmHash,
			&i.EscrowGeneratedAt,
			&i.EscrowConfirmedAt,
			&i.EscrowConfirmedBy,
			&i.LastReindexAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeleteAfter,
			&i.DeleteReason,
			&i.LastVerifiedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleRecoveryPointDeletion = `-- name: ScheduleRecoveryPointDeletion :one
UPDATE recovery_points SET delete_after = $3, delete_reason = $4, delete_requested_by = $5, updated_at = now()
WHERE id = $1 AND org_id = $2 AND state IN ('committed', 'missing') AND delete_after IS NULL
RETURNING id, org_id, repository_id, application_id, application_name, agent_id, hostname, state, status, verification, consistency_mode, consistency_point, crash_consistent_only, trigger, requested_by, workflow_id, run_id, size_bytes, component_count, manifest, manifest_snapshot_id, error, created_at, committed_at, updated_at, delete_after, delete_reason, delete_requested_by, deleted_at, verified_at, verification_details
`

type ScheduleRecoveryPointDeletionParams struct {
	ID                string
	OrgID             uuid.UUID
	DeleteAfter       *time.Time
	DeleteReason      *string
	DeleteRequestedBy *uuid.UUID
}

func (q *Queries) ScheduleRecoveryPointDeletion(ctx context.Context, arg ScheduleRecoveryPointDeletionParams) (RecoveryPoint, error) {
	row := q.db.QueryRow(ctx, scheduleRecoveryPointDeletion,
		arg.ID,
		arg.OrgID,
		arg.DeleteAfter,
		arg.DeleteReason,
		arg.DeleteRequestedBy,
	)
	var i RecoveryPoint
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RepositoryID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.AgentID,
		&i.Hostname,
		&i.State,
		&i.Status,
		&i.Verification,
		&i.ConsistencyMode,
		&i.ConsistencyPoint,
		&i.CrashConsistentOnly,
		&i.Trigger,
		&i.RequestedBy,
		&i.WorkflowID,
		&i.RunID,
		&i.SizeBytes,
		&i.ComponentCount,
		&i.Manifest,
		&i.ManifestSnapshotID,
		&i.Error,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.DeleteRequestedBy,
		&i.DeletedAt,
		&i.VerifiedAt,
		&i.VerificationDetails,
	)
	return i, err
}

const scheduleRepositoryDeletion = `-- name: ScheduleRepositoryDeletion :one
UPDATE repositories SET status = 'pending_deletion', delete_after = $3, delete_reason = $4, is_default = false, updated_at = now()
WHERE id = $1 AND org_id = $2 AND status IN ('ready', 'awaiting_escrow', 'unavailable')
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

type ScheduleRepositoryDeletionParams struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	DeleteAfter  *time.Time
	DeleteReason *string
}

func (q *Queries) ScheduleRepositoryDeletion(ctx context.Context, arg ScheduleRepositoryDeletionParams) (Repository, error) {
	row := q.db.QueryRow(ctx, scheduleRepositoryDeletion,
		arg.ID,
		arg.OrgID,
		arg.DeleteAfter,
		arg.DeleteReason,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const setApplicationPolicy = `-- name: SetApplicationPolicy :execrows
UPDATE applications SET policy_id = $3, updated_at = now() WHERE id = $1 AND org_id = $2
`

type SetApplicationPolicyParams struct {
	ID       uuid.UUID
	OrgID    uuid.UUID
	PolicyID *uuid.UUID
}

func (q *Queries) SetApplicationPolicy(ctx context.Context, arg SetApplicationPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setApplicationPolicy, arg.ID, arg.OrgID, arg.PolicyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContractState = `-- name: SetContractState :exec
UPDATE recovery_contracts SET state = $2, state_reasons = $3, evaluated_at = now(),
    violated_since = CASE WHEN $2 = 'violated' THEN coalesce(violated_since, now()) ELSE NULL END
WHERE application_id = $1
`

type SetContractStateParams struct {
	ApplicationID uuid.UUID
	State         string
	StateReasons  []string
}

func (q *Queries) SetContractState(ctx context.Context, arg SetContractStateParams) error {
	_, err := q.db.Exec(ctx, setContractState, arg.ApplicationID, arg.State, arg.StateReasons)
	return err
}

const setRecoveryPointVerification = `-- name: SetRecoveryPointVerification :exec
UPDATE recovery_points SET verification = $2, verified_at = now(), verification_details = $3, updated_at = now() WHERE id = $1
`

type SetRecoveryPointVerificationParams struct {
	ID                  string
	Verification        string
	VerificationDetails json.RawMessage
}

func (q *Queries) SetRecoveryPointVerification(ctx context.Context, arg SetRecoveryPointVerificationParams) error {
	_, err := q.db.Exec(ctx, setRecoveryPointVerification, arg.ID, arg.Verification, arg.VerificationDetails)
	return err
}

const setRepositoryVerified = `-- name: SetRepositoryVerified :exec
UPDATE repositories SET last_verified_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetRepositoryVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRepositoryVerified, id)
	return err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE protection_policies SET name = $3, description = $4, schedule = $5, timezone = $6, enabled = $7,
    consistency_mode = $8, repository_id = $9, keep_last = $10, keep_hourly = $11, keep_daily = $12,
    keep_weekly = $13, keep_monthly = $14, keep_yearly = $15, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, schedule, timezone, enabled, consistency_mode, repository_id, keep_last, keep_hourly, keep_daily, keep_weekly, keep_monthly, keep_yearly, created_by, created_at, updated_at
`

type UpdatePolicyParams struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	Name            string
	Description     string
	Schedule        string
	Timezone        string
	Enabled         bool
	ConsistencyMode *string
	RepositoryID    *uuid.UUID
	KeepLast        int32
	KeepHourly      int32
	KeepDaily       int32
	KeepWeekly      int32
	KeepMonthly     int32
	KeepYearly      int32
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (ProtectionPolicy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Schedule,
		arg.Timezone,
		arg.Enabled,
		arg.ConsistencyMode,
		arg.RepositoryID,
		arg.KeepLast,
		arg.KeepHourly,
		arg.KeepDaily,
		arg.KeepWeekly,
		arg.KeepMonthly,
		arg.KeepYearly,
	)
	var i ProtectionPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Schedule,
		&i.Timezone,
		&i.Enabled,
		&i.ConsistencyMode,
		&i.RepositoryID,
		&i.KeepLast,
		&i.KeepHourly,
		&i.KeepDaily,
		&i.KeepWeekly,
		&i.KeepMonthly,
		&i.KeepYearly,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContract = `-- name: UpsertContract :one
INSERT INTO recovery_contracts (application_id, max_rpo_minutes, required_components, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (application_id) DO UPDATE SET max_rpo_minutes = EXCLUDED.max_rpo_minutes,
    required_components = EXCLUDED.required_components, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING application_id, max_rpo_minutes, required_components, state, state_reasons, evaluated_at, violated_since, updated_by, updated_at
`

type UpsertContractParams struct {
	ApplicationID      uuid.UUID
	MaxRpoMinutes      *int32
	RequiredComponents []string
	UpdatedBy          *uuid.UUID
}

func (q *Queries) UpsertContract(ctx context.Context, arg UpsertContractParams) (RecoveryContract, error) {
	row := q.db.QueryRow(ctx, upsertContract,
		arg.ApplicationID,
		arg.MaxRpoMinutes,
		arg.RequiredComponents,
		arg.UpdatedBy,
	)
	var i RecoveryContract
	err := row.Scan(
		&i.ApplicationID,
		&i.MaxRpoMinutes,
		&i.RequiredComponents,
		&i.State,
		&i.StateReasons,
		&i.EvaluatedAt,
		&i.ViolatedSince,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
