// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddGroupMapping(ctx context.Context, arg AddGroupMappingParams) error
	AddUserRole(ctx context.Context, arg AddUserRoleParams) error
	// Rejects replay: a TOTP time step can be used at most once.
	AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (int64, error)
	ConsumeOIDCAuthRequest(ctx context.Context, state string) (OidcAuthRequest, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error)
	// SPDX-License-Identifier: Apache-2.0
	CreateLocalCredential(ctx context.Context, arg CreateLocalCredentialParams) error
	CreateMasterAdmin(ctx context.Context, arg CreateMasterAdminParams) (User, error)
	CreateOIDCAuthRequest(ctx context.Context, arg CreateOIDCAuthRequestParams) error
	CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (User, error)
	// SPDX-License-Identifier: Apache-2.0
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteExpiredOIDCAuthRequests(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteGroupMapping(ctx context.Context, arg DeleteGroupMappingParams) (int64, error)
	DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error
	DeleteUserRolesBySource(ctx context.Context, arg DeleteUserRolesBySourceParams) error
	DisableTOTP(ctx context.Context, userID uuid.UUID) error
	EnableTOTP(ctx context.Context, arg EnableTOTPParams) error
	EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error
	GetActiveAPIToken(ctx context.Context, tokenHash []byte) (GetActiveAPITokenRow, error)
	GetActiveSession(ctx context.Context, id []byte) (GetActiveSessionRow, error)
	GetLocalCredential(ctx context.Context, userID uuid.UUID) (LocalCredential, error)
	GetLocalCredentialForUpdate(ctx context.Context, userID uuid.UUID) (LocalCredential, error)
	// SPDX-License-Identifier: Apache-2.0
	GetMasterAdmin(ctx context.Context, orgID uuid.UUID) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error)
	// SPDX-License-Identifier: Apache-2.0
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListGroupMappings(ctx context.Context, orgID uuid.UUID) ([]OidcGroupMapping, error)
	ListGroupMappingsForGroups(ctx context.Context, arg ListGroupMappingsForGroupsParams) ([]string, error)
	ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]ListUserAPITokensRow, error)
	// SPDX-License-Identifier: Apache-2.0
	ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error)
	ListUsers(ctx context.Context, orgID uuid.UUID) ([]User, error)
	RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error
	ResetLoginFailures(ctx context.Context, userID uuid.UUID) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error)
	RevokeSession(ctx context.Context, id []byte) error
	RevokeUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) error
	SetPendingTOTP(ctx context.Context, arg SetPendingTOTPParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	TouchAPIToken(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id []byte) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UpdateOIDCUserProfile(ctx context.Context, arg UpdateOIDCUserProfileParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
