// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const confirmRepositoryEscrow = `-- name: ConfirmRepositoryEscrow :one
UPDATE repositories SET escrow_confirmed_at = now(), escrow_confirmed_by = $3,
    status = CASE WHEN status = 'awaiting_escrow' THEN 'ready' ELSE status END, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

type ConfirmRepositoryEscrowParams struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	EscrowConfirmedBy *uuid.UUID
}

func (q *Queries) ConfirmRepositoryEscrow(ctx context.Context, arg ConfirmRepositoryEscrowParams) (Repository, error) {
	row := q.db.QueryRow(ctx, confirmRepositoryEscrow, arg.ID, arg.OrgID, arg.EscrowConfirmedBy)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const createEscrowRecipient = `-- name: CreateEscrowRecipient :one
INSERT INTO escrow_recipients (org_id, name, public_key, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, public_key, created_by, created_at, removed_at
`

type CreateEscrowRecipientParams struct {
	OrgID     uuid.UUID
	Name      string
	PublicKey string
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateEscrowRecipient(ctx context.Context, arg CreateEscrowRecipientParams) (EscrowRecipient, error) {
	row := q.db.QueryRow(ctx, createEscrowRecipient,
		arg.OrgID,
		arg.Name,
		arg.PublicKey,
		arg.CreatedBy,
	)
	var i EscrowRecipient
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.PublicKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256,
    kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids,
    escrow_confirm_hash, escrow_generated_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'awaiting_escrow', $11, $12, $13, $14, now(), $15)
RETURNING id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system
`

type CreateRepositoryParams struct {
	OrgID              uuid.UUID
	Name               string
	Description        string
	Backend            string
	ManagementUrl      string
	ServerUrl          string
	InternalServerUrl  string
	CertSha256         string
	KopiaRepositoryID  *string
	Splitter           *string
	IsDefault          bool
	EscrowPackage      []byte
	EscrowRecipientIds []uuid.UUID
	EscrowConfirmHash  []byte
	CreatedBy          *uuid.UUID
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Backend,
		arg.ManagementUrl,
		arg.ServerUrl,
		arg.InternalServerUrl,
		arg.CertSha256,
		arg.KopiaRepositoryID,
		arg.Splitter,
		arg.IsDefault,
		arg.EscrowPackage,
		arg.EscrowRecipientIds,
		arg.EscrowConfirmHash,
		arg.CreatedBy,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const deleteAgentRepositoryAccessForAgent = `-- name: DeleteAgentRepositoryAccessForAgent :exec
DELETE FROM agent_repository_access WHERE agent_id = $1
`

func (q *Queries) DeleteAgentRepositoryAccessForAgent(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentRepositoryAccessForAgent, agentID)
	return err
}

const getAgentRepositoryAccess = `-- name: GetAgentRepositoryAccess :one
SELECT agent_id, repository_id, username, hostname, configured_at FROM agent_repository_access WHERE agent_id = $1 AND repository_id = $2
`

type GetAgentRepositoryAccessParams struct {
	AgentID      uuid.UUID
	RepositoryID uuid.UUID
}

func (q *Queries) GetAgentRepositoryAccess(ctx context.Context, arg GetAgentRepositoryAccessParams) (AgentRepositoryAccess, error) {
	row := q.db.QueryRow(ctx, getAgentRepositoryAccess, arg.AgentID, arg.RepositoryID)
	var i AgentRepositoryAccess
	err := row.Scan(
		&i.AgentID,
		&i.RepositoryID,
		&i.Username,
		&i.Hostname,
		&i.ConfiguredAt,
	)
	return i, err
}

const getDefaultRepository = `-- name: GetDefaultRepository :one
SELECT id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system FROM repositories WHERE org_id = $1 AND is_default AND status <> 'retired'
`

func (q *Queries) GetDefaultRepository(ctx context.Context, orgID uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getDefaultRepository, orgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system FROM repositories WHERE id = $1 AND org_id = $2
`

type GetRepositoryParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetRepository(ctx context.Context, arg GetRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, arg.ID, arg.OrgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Backend,
		&i.ManagementUrl,
		&i.ServerUrl,
		&i.InternalServerUrl,
		&i.CertSha256,
		&i.KopiaRepositoryID,
		&i.Splitter,
		&i.Status,
		&i.IsDefault,
		&i.EscrowPackage,
		&i.EscrowRecipientIds,
		&i.EscrowConfirmHash,
		&i.EscrowGeneratedAt,
		&i.EscrowConfirmedAt,
		&i.EscrowConfirmedBy,
		&i.LastReindexAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfter,
		&i.DeleteReason,
		&i.LastVerifiedAt,
		&i.IsSystem,
	)
	return i, err
}

const listAgentRepositoryAccessForAgent = `-- name: ListAgentRepositoryAccessForAgent :many
SELECT agent_id, repository_id, username, hostname, configured_at FROM agent_repository_access WHERE agent_id = $1
`

func (q *Queries) ListAgentRepositoryAccessForAgent(ctx context.Context, agentID uuid.UUID) ([]AgentRepositoryAccess, error) {
	rows, err := q.db.Query(ctx, listAgentRepositoryAccessForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRepositoryAccess
	for rows.Next() {
		var i AgentRepositoryAccess
		if err := rows.Scan(
			&i.AgentID,
			&i.RepositoryID,
			&i.Username,
			&i.Hostname,
			&i.ConfiguredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscrowRecipients = `-- name: ListEscrowRecipients :many

SELECT id, org_id, name, public_key, created_by, created_at, removed_at FROM escrow_recipients WHERE org_id = $1 AND removed_at IS NULL ORDER BY created_at
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) ListEscrowRecipients(ctx context.Context, orgID uuid.UUID) ([]EscrowRecipient, error) {
	rows, err := q.db.Query(ctx, listEscrowRecipients, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EscrowRecipient
	for rows.Next() {
		var i EscrowRecipient
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.PublicKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, org_id, name, description, backend, management_url, server_url, internal_server_url, cert_sha256, kopia_repository_id, splitter, status, is_default, escrow_package, escrow_recipient_ids, escrow_confirm_hash, escrow_generated_at, escrow_confirmed_at, escrow_confirmed_by, last_reindex_at, created_by, created_at, updated_at, delete_after, delete_reason, last_verified_at, is_system FROM repositories WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListRepositories(ctx context.Context, orgID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Backend,
			&i.ManagementUrl,
			&i.ServerUrl,
			&i.InternalServerUrl,
			&i.CertSha256,
			&i.KopiaRepositoryID,
			&i.Splitter,
			&i.Status,
			&i.IsDefault,
			&i.EscrowPackage,
			&i.EscrowRecipientIds,
			&i.EscrowConfirmHash,
			&i.EscrowGeneratedAt,
			&i.EscrowConfirmedAt,
			&i.EscrowConfirmedBy,
			&i.LastReindexAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeleteAfter,
			&i.DeleteReason,
			&i.LastVerifiedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEscrowRecipient = `-- name: RemoveEscrowRecipient :execrows
UPDATE escrow_recipients SET removed_at = now() WHERE id = $1 AND org_id = $2 AND removed_at IS NULL
`

type RemoveEscrowRecipientParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) RemoveEscrowRecipient(ctx context.Context, arg RemoveEscrowRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeEscrowRecipient, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const repositoryUsageByHost = `-- name: RepositoryUsageByHost :many
SELECT agent_id, hostname, count(*)::int AS applications, sum(size_bytes)::bigint AS latest_bytes
FROM (
    SELECT DISTINCT ON (application_id) application_id, agent_id, hostname, size_bytes
    FROM recovery_points
    WHERE repository_id = $1 AND state = 'committed'
    ORDER BY application_id, created_at DESC
) latest
GROUP BY agent_id, hostname
ORDER BY hostname
`

type RepositoryUsageByHostRow struct {
	AgentID      uuid.UUID
	Hostname     string
	Applications int32
	LatestBytes  int64
}

// Logical size of the latest committed recovery point of every application,
// summed per host (physical usage is not attributable under deduplication).
func (q *Queries) RepositoryUsageByHost(ctx context.Context, repositoryID uuid.UUID) ([]RepositoryUsageByHostRow, error) {
	rows, err := q.db.Query(ctx, repositoryUsageByHost, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryUsageByHostRow
	for rows.Next() {
		var i RepositoryUsageByHostRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Hostname,
			&i.Applications,
			&i.LatestBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryReindexed = `-- name: SetRepositoryReindexed :exec
UPDATE repositories SET last_reindex_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetRepositoryReindexed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setRepositoryReindexed, id)
	return err
}

const updateRepositoryConnection = `-- name: UpdateRepositoryConnection :exec
UPDATE repositories SET cert_sha256 = $2, kopia_repository_id = coalesce($3, kopia_repository_id), updated_at = now()
WHERE id = $1
`

type UpdateRepositoryConnectionParams struct {
	ID                uuid.UUID
	CertSha256        string
	KopiaRepositoryID *string
}

func (q *Queries) UpdateRepositoryConnection(ctx context.Context, arg UpdateRepositoryConnectionParams) error {
	_, err := q.db.Exec(ctx, updateRepositoryConnection, arg.ID, arg.CertSha256, arg.KopiaRepositoryID)
	return err
}

const upsertAgentRepositoryAccess = `-- name: UpsertAgentRepositoryAccess :exec
INSERT INTO agent_repository_access (agent_id, repository_id, username, hostname)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, repository_id) DO UPDATE SET username = EXCLUDED.username,
    hostname = EXCLUDED.hostname, configured_at = now()
`

type UpsertAgentRepositoryAccessParams struct {
	AgentID      uuid.UUID
	RepositoryID uuid.UUID
	Username     string
	Hostname     string
}

func (q *Queries) UpsertAgentRepositoryAccess(ctx context.Context, arg UpsertAgentRepositoryAccessParams) error {
	_, err := q.db.Exec(ctx, upsertAgentRepositoryAccess,
		arg.AgentID,
		arg.RepositoryID,
		arg.Username,
		arg.Hostname,
	)
	return err
}
