// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restores.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createRestoreRun = `-- name: CreateRestoreRun :one

INSERT INTO restore_runs (id, org_id, recovery_point_id, repository_id, source_application_id, application_name,
    source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components,
    path_remaps, preview, reason, requested_by, requested_by_display)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, org_id, recovery_point_id, repository_id, source_application_id, application_name, source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components, path_remaps, preview, reason, requested_by, requested_by_display, state, step, result, error, workflow_id, run_id, grant_id, created_at, started_at, finished_at, updated_at
`

type CreateRestoreRunParams struct {
	ID                  string
	OrgID               uuid.UUID
	RecoveryPointID     string
	RepositoryID        uuid.UUID
	SourceApplicationID uuid.UUID
	ApplicationName     string
	SourceAgentID       uuid.UUID
	SourceHostname      string
	TargetAgentID       uuid.UUID
	TargetHostname      string
	TargetApplicationID *uuid.UUID
	Mode                string
	Production          bool
	Components          []string
	PathRemaps          json.RawMessage
	Preview             json.RawMessage
	Reason              *string
	RequestedBy         *uuid.UUID
	RequestedByDisplay  string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateRestoreRun(ctx context.Context, arg CreateRestoreRunParams) (RestoreRun, error) {
	row := q.db.QueryRow(ctx, createRestoreRun,
		arg.ID,
		arg.OrgID,
		arg.RecoveryPointID,
		arg.RepositoryID,
		arg.SourceApplicationID,
		arg.ApplicationName,
		arg.SourceAgentID,
		arg.SourceHostname,
		arg.TargetAgentID,
		arg.TargetHostname,
		arg.TargetApplicationID,
		arg.Mode,
		arg.Production,
		arg.Components,
		arg.PathRemaps,
		arg.Preview,
		arg.Reason,
		arg.RequestedBy,
		arg.RequestedByDisplay,
	)
	var i RestoreRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecoveryPointID,
		&i.RepositoryID,
		&i.SourceApplicationID,
		&i.ApplicationName,
		&i.SourceAgentID,
		&i.SourceHostname,
		&i.TargetAgentID,
		&i.TargetHostname,
		&i.TargetApplicationID,
		&i.Mode,
		&i.Production,
		&i.Components,
		&i.PathRemaps,
		&i.Preview,
		&i.Reason,
		&i.RequestedBy,
		&i.RequestedByDisplay,
		&i.State,
		&i.Step,
		&i.Result,
		&i.Error,
		&i.WorkflowID,
		&i.RunID,
		&i.GrantID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishRestoreRun = `-- name: FinishRestoreRun :one
UPDATE restore_runs SET state = $2, result = coalesce($3, result), error = $4, finished_at = now(), updated_at = now()
WHERE id = $1 AND state IN ('requested', 'running')
RETURNING id, org_id, recovery_point_id, repository_id, source_application_id, application_name, source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components, path_remaps, preview, reason, requested_by, requested_by_display, state, step, result, error, workflow_id, run_id, grant_id, created_at, started_at, finished_at, updated_at
`

type FinishRestoreRunParams struct {
	ID     string
	State  string
	Result json.RawMessage
	Error  *string
}

func (q *Queries) FinishRestoreRun(ctx context.Context, arg FinishRestoreRunParams) (RestoreRun, error) {
	row := q.db.QueryRow(ctx, finishRestoreRun,
		arg.ID,
		arg.State,
		arg.Result,
		arg.Error,
	)
	var i RestoreRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecoveryPointID,
		&i.RepositoryID,
		&i.SourceApplicationID,
		&i.ApplicationName,
		&i.SourceAgentID,
		&i.SourceHostname,
		&i.TargetAgentID,
		&i.TargetHostname,
		&i.TargetApplicationID,
		&i.Mode,
		&i.Production,
		&i.Components,
		&i.PathRemaps,
		&i.Preview,
		&i.Reason,
		&i.RequestedBy,
		&i.RequestedByDisplay,
		&i.State,
		&i.Step,
		&i.Result,
		&i.Error,
		&i.WorkflowID,
		&i.RunID,
		&i.GrantID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestoreRun = `-- name: GetRestoreRun :one
SELECT id, org_id, recovery_point_id, repository_id, source_application_id, application_name, source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components, path_remaps, preview, reason, requested_by, requested_by_display, state, step, result, error, workflow_id, run_id, grant_id, created_at, started_at, finished_at, updated_at FROM restore_runs WHERE id = $1 AND org_id = $2
`

type GetRestoreRunParams struct {
	ID    string
	OrgID uuid.UUID
}

func (q *Queries) GetRestoreRun(ctx context.Context, arg GetRestoreRunParams) (RestoreRun, error) {
	row := q.db.QueryRow(ctx, getRestoreRun, arg.ID, arg.OrgID)
	var i RestoreRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecoveryPointID,
		&i.RepositoryID,
		&i.SourceApplicationID,
		&i.ApplicationName,
		&i.SourceAgentID,
		&i.SourceHostname,
		&i.TargetAgentID,
		&i.TargetHostname,
		&i.TargetApplicationID,
		&i.Mode,
		&i.Production,
		&i.Components,
		&i.PathRemaps,
		&i.Preview,
		&i.Reason,
		&i.RequestedBy,
		&i.RequestedByDisplay,
		&i.State,
		&i.Step,
		&i.Result,
		&i.Error,
		&i.WorkflowID,
		&i.RunID,
		&i.GrantID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestoreRunByID = `-- name: GetRestoreRunByID :one
SELECT id, org_id, recovery_point_id, repository_id, source_application_id, application_name, source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components, path_remaps, preview, reason, requested_by, requested_by_display, state, step, result, error, workflow_id, run_id, grant_id, created_at, started_at, finished_at, updated_at FROM restore_runs WHERE id = $1
`

func (q *Queries) GetRestoreRunByID(ctx context.Context, id string) (RestoreRun, error) {
	row := q.db.QueryRow(ctx, getRestoreRunByID, id)
	var i RestoreRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecoveryPointID,
		&i.RepositoryID,
		&i.SourceApplicationID,
		&i.ApplicationName,
		&i.SourceAgentID,
		&i.SourceHostname,
		&i.TargetAgentID,
		&i.TargetHostname,
		&i.TargetApplicationID,
		&i.Mode,
		&i.Production,
		&i.Components,
		&i.PathRemaps,
		&i.Preview,
		&i.Reason,
		&i.RequestedBy,
		&i.RequestedByDisplay,
		&i.State,
		&i.Step,
		&i.Result,
		&i.Error,
		&i.WorkflowID,
		&i.RunID,
		&i.GrantID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRestoreRuns = `-- name: ListRestoreRuns :many
SELECT id, org_id, recovery_point_id, repository_id, source_application_id, application_name, source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components, path_remaps, preview, reason, requested_by, requested_by_display, state, step, result, error, workflow_id, run_id, grant_id, created_at, started_at, finished_at, updated_at FROM restore_runs
WHERE org_id = $1
  AND ($3::uuid IS NULL OR source_application_id = $3
       OR target_application_id = $3)
  AND ($4::text IS NULL OR state = $4)
ORDER BY created_at DESC
LIMIT $2
`

type ListRestoreRunsParams struct {
	OrgID         uuid.UUID
	Limit         int32
	ApplicationID *uuid.UUID
	State         *string
}

func (q *Queries) ListRestoreRuns(ctx context.Context, arg ListRestoreRunsParams) ([]RestoreRun, error) {
	rows, err := q.db.Query(ctx, listRestoreRuns,
		arg.OrgID,
		arg.Limit,
		arg.ApplicationID,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestoreRun
	for rows.Next() {
		var i RestoreRun
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RecoveryPointID,
			&i.RepositoryID,
			&i.SourceApplicationID,
			&i.ApplicationName,
			&i.SourceAgentID,
			&i.SourceHostname,
			&i.TargetAgentID,
			&i.TargetHostname,
			&i.TargetApplicationID,
			&i.Mode,
			&i.Production,
			&i.Components,
			&i.PathRemaps,
			&i.Preview,
			&i.Reason,
			&i.RequestedBy,
			&i.RequestedByDisplay,
			&i.State,
			&i.Step,
			&i.Result,
			&i.Error,
			&i.WorkflowID,
			&i.RunID,
			&i.GrantID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRestoreGrant = `-- name: SetRestoreGrant :exec
UPDATE restore_runs SET grant_id = $2, updated_at = now() WHERE id = $1
`

type SetRestoreGrantParams struct {
	ID      string
	GrantID *string
}

func (q *Queries) SetRestoreGrant(ctx context.Context, arg SetRestoreGrantParams) error {
	_, err := q.db.Exec(ctx, setRestoreGrant, arg.ID, arg.GrantID)
	return err
}

const setRestoreStep = `-- name: SetRestoreStep :exec
UPDATE restore_runs SET step = $2, updated_at = now() WHERE id = $1 AND state = 'running'
`

type SetRestoreStepParams struct {
	ID   string
	Step *string
}

func (q *Queries) SetRestoreStep(ctx context.Context, arg SetRestoreStepParams) error {
	_, err := q.db.Exec(ctx, setRestoreStep, arg.ID, arg.Step)
	return err
}

const setRestoreWorkflow = `-- name: SetRestoreWorkflow :exec
UPDATE restore_runs SET workflow_id = $2, run_id = $3, updated_at = now() WHERE id = $1
`

type SetRestoreWorkflowParams struct {
	ID         string
	WorkflowID *string
	RunID      *string
}

func (q *Queries) SetRestoreWorkflow(ctx context.Context, arg SetRestoreWorkflowParams) error {
	_, err := q.db.Exec(ctx, setRestoreWorkflow, arg.ID, arg.WorkflowID, arg.RunID)
	return err
}

const startRestoreRun = `-- name: StartRestoreRun :one
UPDATE restore_runs SET state = 'running', started_at = coalesce(started_at, now()), workflow_id = $2, run_id = $3,
    updated_at = now()
WHERE id = $1 AND state IN ('requested', 'running')
RETURNING id, org_id, recovery_point_id, repository_id, source_application_id, application_name, source_agent_id, source_hostname, target_agent_id, target_hostname, target_application_id, mode, production, components, path_remaps, preview, reason, requested_by, requested_by_display, state, step, result, error, workflow_id, run_id, grant_id, created_at, started_at, finished_at, updated_at
`

type StartRestoreRunParams struct {
	ID         string
	WorkflowID *string
	RunID      *string
}

func (q *Queries) StartRestoreRun(ctx context.Context, arg StartRestoreRunParams) (RestoreRun, error) {
	row := q.db.QueryRow(ctx, startRestoreRun, arg.ID, arg.WorkflowID, arg.RunID)
	var i RestoreRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RecoveryPointID,
		&i.RepositoryID,
		&i.SourceApplicationID,
		&i.ApplicationName,
		&i.SourceAgentID,
		&i.SourceHostname,
		&i.TargetAgentID,
		&i.TargetHostname,
		&i.TargetApplicationID,
		&i.Mode,
		&i.Production,
		&i.Components,
		&i.PathRemaps,
		&i.Preview,
		&i.Reason,
		&i.RequestedBy,
		&i.RequestedByDisplay,
		&i.State,
		&i.Step,
		&i.Result,
		&i.Error,
		&i.WorkflowID,
		&i.RunID,
		&i.GrantID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
