// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addGroupMapping = `-- name: AddGroupMapping :exec
INSERT INTO oidc_group_mappings (org_id, provider, group_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddGroupMappingParams struct {
	OrgID    uuid.UUID
	Provider string
	GroupID  string
	Role     string
}

func (q *Queries) AddGroupMapping(ctx context.Context, arg AddGroupMappingParams) error {
	_, err := q.db.Exec(ctx, addGroupMapping,
		arg.OrgID,
		arg.Provider,
		arg.GroupID,
		arg.Role,
	)
	return err
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role, source, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID    uuid.UUID
	Role      string
	Source    string
	GrantedBy *uuid.UUID
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole,
		arg.UserID,
		arg.Role,
		arg.Source,
		arg.GrantedBy,
	)
	return err
}

const deleteGroupMapping = `-- name: DeleteGroupMapping :execrows
DELETE FROM oidc_group_mappings WHERE org_id = $1 AND provider = $2 AND group_id = $3 AND role = $4
`

type DeleteGroupMappingParams struct {
	OrgID    uuid.UUID
	Provider string
	GroupID  string
	Role     string
}

func (q *Queries) DeleteGroupMapping(ctx context.Context, arg DeleteGroupMappingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroupMapping,
		arg.OrgID,
		arg.Provider,
		arg.GroupID,
		arg.Role,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role = $2 AND source = $3
`

type DeleteUserRoleParams struct {
	UserID uuid.UUID
	Role   string
	Source string
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.Exec(ctx, deleteUserRole, arg.UserID, arg.Role, arg.Source)
	return err
}

const deleteUserRolesBySource = `-- name: DeleteUserRolesBySource :exec
DELETE FROM user_roles WHERE user_id = $1 AND source = $2
`

type DeleteUserRolesBySourceParams struct {
	UserID uuid.UUID
	Source string
}

func (q *Queries) DeleteUserRolesBySource(ctx context.Context, arg DeleteUserRolesBySourceParams) error {
	_, err := q.db.Exec(ctx, deleteUserRolesBySource, arg.UserID, arg.Source)
	return err
}

const listGroupMappings = `-- name: ListGroupMappings :many
SELECT org_id, provider, group_id, role, created_at FROM oidc_group_mappings WHERE org_id = $1 ORDER BY provider, group_id, role
`

func (q *Queries) ListGroupMappings(ctx context.Context, orgID uuid.UUID) ([]OidcGroupMapping, error) {
	rows, err := q.db.Query(ctx, listGroupMappings, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcGroupMapping
	for rows.Next() {
		var i OidcGroupMapping
		if err := rows.Scan(
			&i.OrgID,
			&i.Provider,
			&i.GroupID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMappingsForGroups = `-- name: ListGroupMappingsForGroups :many
SELECT role FROM oidc_group_mappings
WHERE org_id = $1 AND provider = $2 AND group_id = ANY($3::text[])
`

type ListGroupMappingsForGroupsParams struct {
	OrgID    uuid.UUID
	Provider string
	GroupIds []string
}

func (q *Queries) ListGroupMappingsForGroups(ctx context.Context, arg ListGroupMappingsForGroupsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listGroupMappingsForGroups, arg.OrgID, arg.Provider, arg.GroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many

SELECT role, source FROM user_roles WHERE user_id = $1 ORDER BY role, source
`

type ListUserRolesRow struct {
	Role   string
	Source string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRolesRow
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.Role, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
