// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeOIDCAuthRequest = `-- name: ConsumeOIDCAuthRequest :one
DELETE FROM oidc_auth_requests WHERE state = $1 AND expires_at > now()
RETURNING state, provider, nonce, code_verifier, return_to, created_at, expires_at
`

func (q *Queries) ConsumeOIDCAuthRequest(ctx context.Context, state string) (OidcAuthRequest, error) {
	row := q.db.QueryRow(ctx, consumeOIDCAuthRequest, state)
	var i OidcAuthRequest
	err := row.Scan(
		&i.State,
		&i.Provider,
		&i.Nonce,
		&i.CodeVerifier,
		&i.ReturnTo,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, prefix, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID
	Name      string
	TokenHash []byte
	Prefix    string
	ExpiresAt *time.Time
}

type CreateAPITokenRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Prefix     string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createOIDCAuthRequest = `-- name: CreateOIDCAuthRequest :exec
INSERT INTO oidc_auth_requests (state, provider, nonce, code_verifier, return_to, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOIDCAuthRequestParams struct {
	State        string
	Provider     string
	Nonce        string
	CodeVerifier string
	ReturnTo     string
	ExpiresAt    time.Time
}

func (q *Queries) CreateOIDCAuthRequest(ctx context.Context, arg CreateOIDCAuthRequestParams) error {
	_, err := q.db.Exec(ctx, createOIDCAuthRequest,
		arg.State,
		arg.Provider,
		arg.Nonce,
		arg.CodeVerifier,
		arg.ReturnTo,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, user_id, auth_method, expires_at, source_ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID         []byte
	UserID     uuid.UUID
	AuthMethod string
	ExpiresAt  time.Time
	SourceIp   *netip.Addr
	UserAgent  *string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AuthMethod,
		arg.ExpiresAt,
		arg.SourceIp,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredOIDCAuthRequests = `-- name: DeleteExpiredOIDCAuthRequests :execrows
DELETE FROM oidc_auth_requests WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOIDCAuthRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCAuthRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAPIToken = `-- name: GetActiveAPIToken :one
SELECT t.id, t.user_id FROM api_tokens t JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now()) AND NOT u.disabled
`

type GetActiveAPITokenRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetActiveAPIToken(ctx context.Context, tokenHash []byte) (GetActiveAPITokenRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIToken, tokenHash)
	var i GetActiveAPITokenRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id, s.user_id, s.auth_method, s.expires_at, s.last_seen_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.revoked_at IS NULL AND s.expires_at > now() AND NOT u.disabled
`

type GetActiveSessionRow struct {
	ID         []byte
	UserID     uuid.UUID
	AuthMethod string
	ExpiresAt  time.Time
	LastSeenAt time.Time
}

func (q *Queries) GetActiveSession(ctx context.Context, id []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, id)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthMethod,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, user_id, name, prefix, created_at, expires_at, last_used_at, revoked_at
FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

type ListUserAPITokensRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Prefix     string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]ListUserAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAPITokensRow
	for rows.Next() {
		var i ListUserAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const revokeUserSessionsExcept = `-- name: RevokeUserSessionsExcept :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeUserSessionsExceptParams struct {
	UserID uuid.UUID
	ID     []byte
}

func (q *Queries) RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionsExcept, arg.UserID, arg.ID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
