// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMasterAdmin = `-- name: CreateMasterAdmin :one
INSERT INTO users (org_id, kind, username, display_name)
VALUES ($1, 'master_admin', $2, $3)
RETURNING id, org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject, disabled, created_at, updated_at, last_login_at
`

type CreateMasterAdminParams struct {
	OrgID       uuid.UUID
	Username    string
	DisplayName string
}

func (q *Queries) CreateMasterAdmin(ctx context.Context, arg CreateMasterAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createMasterAdmin, arg.OrgID, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.OidcProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createOIDCUser = `-- name: CreateOIDCUser :one
INSERT INTO users (org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject)
VALUES ($1, 'oidc', $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject, disabled, created_at, updated_at, last_login_at
`

type CreateOIDCUserParams struct {
	OrgID        uuid.UUID
	Username     string
	DisplayName  string
	Email        *string
	OidcProvider *string
	OidcIssuer   *string
	OidcSubject  *string
}

func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOIDCUser,
		arg.OrgID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.OidcProvider,
		arg.OidcIssuer,
		arg.OidcSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.OidcProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getMasterAdmin = `-- name: GetMasterAdmin :one

SELECT id, org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject, disabled, created_at, updated_at, last_login_at FROM users WHERE org_id = $1 AND kind = 'master_admin'
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetMasterAdmin(ctx context.Context, orgID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getMasterAdmin, orgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.OidcProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject, disabled, created_at, updated_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.OidcProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByOIDC = `-- name: GetUserByOIDC :one
SELECT id, org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject, disabled, created_at, updated_at, last_login_at FROM users
WHERE org_id = $1 AND kind = 'oidc' AND oidc_issuer = $2 AND oidc_subject = $3
`

type GetUserByOIDCParams struct {
	OrgID       uuid.UUID
	OidcIssuer  *string
	OidcSubject *string
}

func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDC, arg.OrgID, arg.OidcIssuer, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.OidcProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, org_id, kind, username, display_name, email, oidc_provider, oidc_issuer, oidc_subject, disabled, created_at, updated_at, last_login_at FROM users WHERE org_id = $1 ORDER BY kind, lower(display_name)
`

func (q *Queries) ListUsers(ctx context.Context, orgID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.OidcProvider,
			&i.OidcIssuer,
			&i.OidcSubject,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET disabled = $2, updated_at = now() WHERE id = $1 AND kind <> 'master_admin'
`

type SetUserDisabledParams struct {
	ID       uuid.UUID
	Disabled bool
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.Disabled)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateOIDCUserProfile = `-- name: UpdateOIDCUserProfile :exec
UPDATE users SET username = $2, display_name = $3, email = $4, updated_at = now()
WHERE id = $1
`

type UpdateOIDCUserProfileParams struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Email       *string
}

func (q *Queries) UpdateOIDCUserProfile(ctx context.Context, arg UpdateOIDCUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateOIDCUserProfile,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
	)
	return err
}
