// SPDX-License-Identifier: Apache-2.0

// Internal control plane protocol between dbr2-worker (Temporal activities)
// and the Agent Gateway in dbr2-server (ADR-0001). Not exposed outside the
// deployment network; authenticated with the internal token.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayControlService_Dispatch_FullMethodName = "/control.v1.GatewayControlService/Dispatch"
)

// GatewayControlServiceClient is the client API for GatewayControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayControlService dispatches commands to connected agents.
type GatewayControlServiceClient interface {
	// Dispatch sends a command to an agent and streams its updates until the
	// terminal result. If the agent is offline, the gateway waits up to
	// wait_for_agent_seconds for it to reconnect. Re-dispatching the same
	// command_id is idempotent.
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchResponse], error)
}

type gatewayControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlServiceClient(cc grpc.ClientConnInterface) GatewayControlServiceClient {
	return &gatewayControlServiceClient{cc}
}

func (c *gatewayControlServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayControlService_ServiceDesc.Streams[0], GatewayControlService_Dispatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchRequest, DispatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlService_DispatchClient = grpc.ServerStreamingClient[DispatchResponse]

// GatewayControlServiceServer is the server API for GatewayControlService service.
// All implementations must embed UnimplementedGatewayControlServiceServer
// for forward compatibility.
//
// GatewayControlService dispatches commands to connected agents.
type GatewayControlServiceServer interface {
	// Dispatch sends a command to an agent and streams its updates until the
	// terminal result. If the agent is offline, the gateway waits up to
	// wait_for_agent_seconds for it to reconnect. Re-dispatching the same
	// command_id is idempotent.
	Dispatch(*DispatchRequest, grpc.ServerStreamingServer[DispatchResponse]) error
	mustEmbedUnimplementedGatewayControlServiceServer()
}

// UnimplementedGatewayControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlServiceServer struct{}

func (UnimplementedGatewayControlServiceServer) Dispatch(*DispatchRequest, grpc.ServerStreamingServer[DispatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedGatewayControlServiceServer) mustEmbedUnimplementedGatewayControlServiceServer() {}
func (UnimplementedGatewayControlServiceServer) testEmbeddedByValue()                               {}

// UnsafeGatewayControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlServiceServer will
// result in compilation errors.
type UnsafeGatewayControlServiceServer interface {
	mustEmbedUnimplementedGatewayControlServiceServer()
}

func RegisterGatewayControlServiceServer(s grpc.ServiceRegistrar, srv GatewayControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControlService_ServiceDesc, srv)
}

func _GatewayControlService_Dispatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayControlServiceServer).Dispatch(m, &grpc.GenericServerStream[DispatchRequest, DispatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlService_DispatchServer = grpc.ServerStreamingServer[DispatchResponse]

// GatewayControlService_ServiceDesc is the grpc.ServiceDesc for GatewayControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.GatewayControlService",
	HandlerType: (*GatewayControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dispatch",
			Handler:       _GatewayControlService_Dispatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control/v1/control.proto",
}
