// SPDX-License-Identifier: Apache-2.0

// Internal control plane protocol between dbr2-worker (Temporal activities)
// and the Agent Gateway in dbr2-server (ADR-0001). Not exposed outside the
// deployment network; authenticated with the internal token.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayControlService_Dispatch_FullMethodName = "/control.v1.GatewayControlService/Dispatch"
)

// GatewayControlServiceClient is the client API for GatewayControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayControlService dispatches commands to connected agents.
type GatewayControlServiceClient interface {
	// Dispatch sends a command to an agent and streams its updates until the
	// terminal result. If the agent is offline, the gateway waits up to
	// wait_for_agent_seconds for it to reconnect. Re-dispatching the same
	// command_id is idempotent.
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchResponse], error)
}

type gatewayControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlServiceClient(cc grpc.ClientConnInterface) GatewayControlServiceClient {
	return &gatewayControlServiceClient{cc}
}

func (c *gatewayControlServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DispatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayControlService_ServiceDesc.Streams[0], GatewayControlService_Dispatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchRequest, DispatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlService_DispatchClient = grpc.ServerStreamingClient[DispatchResponse]

// GatewayControlServiceServer is the server API for GatewayControlService service.
// All implementations must embed UnimplementedGatewayControlServiceServer
// for forward compatibility.
//
// GatewayControlService dispatches commands to connected agents.
type GatewayControlServiceServer interface {
	// Dispatch sends a command to an agent and streams its updates until the
	// terminal result. If the agent is offline, the gateway waits up to
	// wait_for_agent_seconds for it to reconnect. Re-dispatching the same
	// command_id is idempotent.
	Dispatch(*DispatchRequest, grpc.ServerStreamingServer[DispatchResponse]) error
	mustEmbedUnimplementedGatewayControlServiceServer()
}

// UnimplementedGatewayControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlServiceServer struct{}

func (UnimplementedGatewayControlServiceServer) Dispatch(*DispatchRequest, grpc.ServerStreamingServer[DispatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedGatewayControlServiceServer) mustEmbedUnimplementedGatewayControlServiceServer() {}
func (UnimplementedGatewayControlServiceServer) testEmbeddedByValue()                               {}

// UnsafeGatewayControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlServiceServer will
// result in compilation errors.
type UnsafeGatewayControlServiceServer interface {
	mustEmbedUnimplementedGatewayControlServiceServer()
}

func RegisterGatewayControlServiceServer(s grpc.ServiceRegistrar, srv GatewayControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControlService_ServiceDesc, srv)
}

func _GatewayControlService_Dispatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayControlServiceServer).Dispatch(m, &grpc.GenericServerStream[DispatchRequest, DispatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayControlService_DispatchServer = grpc.ServerStreamingServer[DispatchResponse]

// GatewayControlService_ServiceDesc is the grpc.ServiceDesc for GatewayControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.GatewayControlService",
	HandlerType: (*GatewayControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dispatch",
			Handler:       _GatewayControlService_Dispatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control/v1/control.proto",
}

const (
	PlatformService_PrepareBackup_FullMethodName               = "/control.v1.PlatformService/PrepareBackup"
	PlatformService_EnsureAgentAccess_FullMethodName           = "/control.v1.PlatformService/EnsureAgentAccess"
	PlatformService_CompleteBackup_FullMethodName              = "/control.v1.PlatformService/CompleteBackup"
	PlatformService_GetRepository_FullMethodName               = "/control.v1.PlatformService/GetRepository"
	PlatformService_ListRepositories_FullMethodName            = "/control.v1.PlatformService/ListRepositories"
	PlatformService_IndexRecoveryPoints_FullMethodName         = "/control.v1.PlatformService/IndexRecoveryPoints"
	PlatformService_RecordEvent_FullMethodName                 = "/control.v1.PlatformService/RecordEvent"
	PlatformService_PrepareRestore_FullMethodName              = "/control.v1.PlatformService/PrepareRestore"
	PlatformService_GrantRestoreAccess_FullMethodName          = "/control.v1.PlatformService/GrantRestoreAccess"
	PlatformService_RevokeRestoreAccess_FullMethodName         = "/control.v1.PlatformService/RevokeRestoreAccess"
	PlatformService_UpdateRestore_FullMethodName               = "/control.v1.PlatformService/UpdateRestore"
	PlatformService_ListRetentionCandidates_FullMethodName     = "/control.v1.PlatformService/ListRetentionCandidates"
	PlatformService_BeginRecoveryPointDeletion_FullMethodName  = "/control.v1.PlatformService/BeginRecoveryPointDeletion"
	PlatformService_FinishRecoveryPointDeletion_FullMethodName = "/control.v1.PlatformService/FinishRecoveryPointDeletion"
	PlatformService_ListVerificationCandidates_FullMethodName  = "/control.v1.PlatformService/ListVerificationCandidates"
	PlatformService_SetVerification_FullMethodName             = "/control.v1.PlatformService/SetVerification"
	PlatformService_BeginPlatformBackup_FullMethodName         = "/control.v1.PlatformService/BeginPlatformBackup"
	PlatformService_ExportPlatform_FullMethodName              = "/control.v1.PlatformService/ExportPlatform"
	PlatformService_RecordPlatformBackup_FullMethodName        = "/control.v1.PlatformService/RecordPlatformBackup"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlatformService lets dbr2-worker read and update platform state owned by
// dbr2-server (PostgreSQL, repository management, agent credentials).
type PlatformServiceClient interface {
	// PrepareBackup validates the application, host and Repository, records a
	// pending recovery point and returns the capture plan.
	PrepareBackup(ctx context.Context, in *PrepareBackupRequest, opts ...grpc.CallOption) (*PrepareBackupResponse, error)
	// EnsureAgentAccess makes sure the agent has a Kopia user on the
	// Repository and has been configured with it. Passwords never leave
	// dbr2-server except to the reposerver and the agent.
	EnsureAgentAccess(ctx context.Context, in *EnsureAgentAccessRequest, opts ...grpc.CallOption) (*EnsureAgentAccessResponse, error)
	// CompleteBackup records the outcome of a backup (committed or failed).
	CompleteBackup(ctx context.Context, in *CompleteBackupRequest, opts ...grpc.CallOption) (*CompleteBackupResponse, error)
	// GetRepository returns a Repository's connection details.
	GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*GetRepositoryResponse, error)
	// ListRepositories returns every Repository that is not retired.
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	// IndexRecoveryPoints upserts recovery points found by reindexing.
	IndexRecoveryPoints(ctx context.Context, in *IndexRecoveryPointsRequest, opts ...grpc.CallOption) (*IndexRecoveryPointsResponse, error)
	// RecordEvent records an audit event and alert on behalf of the worker.
	RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error)
	// PrepareRestore marks a requested restore running and returns its plan.
	PrepareRestore(ctx context.Context, in *PrepareRestoreRequest, opts ...grpc.CallOption) (*PrepareRestoreResponse, error)
	// GrantRestoreAccess grants the target agent temporary READ on the
	// source agent's snapshots (cross-host restore); RevokeRestoreAccess
	// removes it (saga compensation).
	GrantRestoreAccess(ctx context.Context, in *GrantRestoreAccessRequest, opts ...grpc.CallOption) (*GrantRestoreAccessResponse, error)
	RevokeRestoreAccess(ctx context.Context, in *RevokeRestoreAccessRequest, opts ...grpc.CallOption) (*RevokeRestoreAccessResponse, error)
	// UpdateRestore records progress (step) and the final outcome.
	UpdateRestore(ctx context.Context, in *UpdateRestoreRequest, opts ...grpc.CallOption) (*UpdateRestoreResponse, error)
	// ListRetentionCandidates returns recovery points to delete now: those
	// outside their policy's retention and manual deletions whose grace
	// period has passed (ADR-0014). Never the latest committed recovery point
	// of an application, never one used by an active restore.
	ListRetentionCandidates(ctx context.Context, in *ListRetentionCandidatesRequest, opts ...grpc.CallOption) (*ListRetentionCandidatesResponse, error)
	// BeginRecoveryPointDeletion marks a recovery point deleting (the worker
	// then deletes the manifest first, then the components, as maint@dbr2).
	BeginRecoveryPointDeletion(ctx context.Context, in *BeginRecoveryPointDeletionRequest, opts ...grpc.CallOption) (*BeginRecoveryPointDeletionResponse, error)
	// FinishRecoveryPointDeletion records the outcome.
	FinishRecoveryPointDeletion(ctx context.Context, in *FinishRecoveryPointDeletionRequest, opts ...grpc.CallOption) (*FinishRecoveryPointDeletionResponse, error)
	// ListVerificationCandidates returns committed recovery points of a
	// Repository to verify, least recently verified first.
	ListVerificationCandidates(ctx context.Context, in *ListVerificationCandidatesRequest, opts ...grpc.CallOption) (*ListVerificationCandidatesResponse, error)
	// SetVerification records a recovery point's verification result.
	SetVerification(ctx context.Context, in *SetVerificationRequest, opts ...grpc.CallOption) (*SetVerificationResponse, error)
	// BeginPlatformBackup records a running Platform Protection run (ADR-0008)
	// and returns its ID and the System Repository (if one is designated).
	BeginPlatformBackup(ctx context.Context, in *BeginPlatformBackupRequest, opts ...grpc.CallOption) (*BeginPlatformBackupResponse, error)
	// ExportPlatform streams the age-encrypted Platform Recovery Bundle
	// (tar -> zstd -> age to every escrow recipient) in ~1 MiB chunks. The
	// bundle is encrypted inside dbr2-server; plaintext never leaves it. The
	// last message carries the summary (plaintext manifest, no secrets).
	ExportPlatform(ctx context.Context, in *ExportPlatformRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportPlatformResponse], error)
	// RecordPlatformBackup stores the outcome of a platform backup (audit
	// event, and an alert when it is partial or failed).
	RecordPlatformBackup(ctx context.Context, in *RecordPlatformBackupRequest, opts ...grpc.CallOption) (*RecordPlatformBackupResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) PrepareBackup(ctx context.Context, in *PrepareBackupRequest, opts ...grpc.CallOption) (*PrepareBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareBackupResponse)
	err := c.cc.Invoke(ctx, PlatformService_PrepareBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) EnsureAgentAccess(ctx context.Context, in *EnsureAgentAccessRequest, opts ...grpc.CallOption) (*EnsureAgentAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureAgentAccessResponse)
	err := c.cc.Invoke(ctx, PlatformService_EnsureAgentAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) CompleteBackup(ctx context.Context, in *CompleteBackupRequest, opts ...grpc.CallOption) (*CompleteBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteBackupResponse)
	err := c.cc.Invoke(ctx, PlatformService_CompleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*GetRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryResponse)
	err := c.cc.Invoke(ctx, PlatformService_GetRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) IndexRecoveryPoints(ctx context.Context, in *IndexRecoveryPointsRequest, opts ...grpc.CallOption) (*IndexRecoveryPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexRecoveryPointsResponse)
	err := c.cc.Invoke(ctx, PlatformService_IndexRecoveryPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEventResponse)
	err := c.cc.Invoke(ctx, PlatformService_RecordEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) PrepareRestore(ctx context.Context, in *PrepareRestoreRequest, opts ...grpc.CallOption) (*PrepareRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareRestoreResponse)
	err := c.cc.Invoke(ctx, PlatformService_PrepareRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GrantRestoreAccess(ctx context.Context, in *GrantRestoreAccessRequest, opts ...grpc.CallOption) (*GrantRestoreAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantRestoreAccessResponse)
	err := c.cc.Invoke(ctx, PlatformService_GrantRestoreAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) RevokeRestoreAccess(ctx context.Context, in *RevokeRestoreAccessRequest, opts ...grpc.CallOption) (*RevokeRestoreAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRestoreAccessResponse)
	err := c.cc.Invoke(ctx, PlatformService_RevokeRestoreAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) UpdateRestore(ctx context.Context, in *UpdateRestoreRequest, opts ...grpc.CallOption) (*UpdateRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRestoreResponse)
	err := c.cc.Invoke(ctx, PlatformService_UpdateRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListRetentionCandidates(ctx context.Context, in *ListRetentionCandidatesRequest, opts ...grpc.CallOption) (*ListRetentionCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRetentionCandidatesResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListRetentionCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) BeginRecoveryPointDeletion(ctx context.Context, in *BeginRecoveryPointDeletionRequest, opts ...grpc.CallOption) (*BeginRecoveryPointDeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginRecoveryPointDeletionResponse)
	err := c.cc.Invoke(ctx, PlatformService_BeginRecoveryPointDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) FinishRecoveryPointDeletion(ctx context.Context, in *FinishRecoveryPointDeletionRequest, opts ...grpc.CallOption) (*FinishRecoveryPointDeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRecoveryPointDeletionResponse)
	err := c.cc.Invoke(ctx, PlatformService_FinishRecoveryPointDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListVerificationCandidates(ctx context.Context, in *ListVerificationCandidatesRequest, opts ...grpc.CallOption) (*ListVerificationCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVerificationCandidatesResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListVerificationCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) SetVerification(ctx context.Context, in *SetVerificationRequest, opts ...grpc.CallOption) (*SetVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVerificationResponse)
	err := c.cc.Invoke(ctx, PlatformService_SetVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) BeginPlatformBackup(ctx context.Context, in *BeginPlatformBackupRequest, opts ...grpc.CallOption) (*BeginPlatformBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginPlatformBackupResponse)
	err := c.cc.Invoke(ctx, PlatformService_BeginPlatformBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ExportPlatform(ctx context.Context, in *ExportPlatformRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportPlatformResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlatformService_ServiceDesc.Streams[0], PlatformService_ExportPlatform_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportPlatformRequest, ExportPlatformResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformService_ExportPlatformClient = grpc.ServerStreamingClient[ExportPlatformResponse]

func (c *platformServiceClient) RecordPlatformBackup(ctx context.Context, in *RecordPlatformBackupRequest, opts ...grpc.CallOption) (*RecordPlatformBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordPlatformBackupResponse)
	err := c.cc.Invoke(ctx, PlatformService_RecordPlatformBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility.
//
// PlatformService lets dbr2-worker read and update platform state owned by
// dbr2-server (PostgreSQL, repository management, agent credentials).
type PlatformServiceServer interface {
	// PrepareBackup validates the application, host and Repository, records a
	// pending recovery point and returns the capture plan.
	PrepareBackup(context.Context, *PrepareBackupRequest) (*PrepareBackupResponse, error)
	// EnsureAgentAccess makes sure the agent has a Kopia user on the
	// Repository and has been configured with it. Passwords never leave
	// dbr2-server except to the reposerver and the agent.
	EnsureAgentAccess(context.Context, *EnsureAgentAccessRequest) (*EnsureAgentAccessResponse, error)
	// CompleteBackup records the outcome of a backup (committed or failed).
	CompleteBackup(context.Context, *CompleteBackupRequest) (*CompleteBackupResponse, error)
	// GetRepository returns a Repository's connection details.
	GetRepository(context.Context, *GetRepositoryRequest) (*GetRepositoryResponse, error)
	// ListRepositories returns every Repository that is not retired.
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	// IndexRecoveryPoints upserts recovery points found by reindexing.
	IndexRecoveryPoints(context.Context, *IndexRecoveryPointsRequest) (*IndexRecoveryPointsResponse, error)
	// RecordEvent records an audit event and alert on behalf of the worker.
	RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error)
	// PrepareRestore marks a requested restore running and returns its plan.
	PrepareRestore(context.Context, *PrepareRestoreRequest) (*PrepareRestoreResponse, error)
	// GrantRestoreAccess grants the target agent temporary READ on the
	// source agent's snapshots (cross-host restore); RevokeRestoreAccess
	// removes it (saga compensation).
	GrantRestoreAccess(context.Context, *GrantRestoreAccessRequest) (*GrantRestoreAccessResponse, error)
	RevokeRestoreAccess(context.Context, *RevokeRestoreAccessRequest) (*RevokeRestoreAccessResponse, error)
	// UpdateRestore records progress (step) and the final outcome.
	UpdateRestore(context.Context, *UpdateRestoreRequest) (*UpdateRestoreResponse, error)
	// ListRetentionCandidates returns recovery points to delete now: those
	// outside their policy's retention and manual deletions whose grace
	// period has passed (ADR-0014). Never the latest committed recovery point
	// of an application, never one used by an active restore.
	ListRetentionCandidates(context.Context, *ListRetentionCandidatesRequest) (*ListRetentionCandidatesResponse, error)
	// BeginRecoveryPointDeletion marks a recovery point deleting (the worker
	// then deletes the manifest first, then the components, as maint@dbr2).
	BeginRecoveryPointDeletion(context.Context, *BeginRecoveryPointDeletionRequest) (*BeginRecoveryPointDeletionResponse, error)
	// FinishRecoveryPointDeletion records the outcome.
	FinishRecoveryPointDeletion(context.Context, *FinishRecoveryPointDeletionRequest) (*FinishRecoveryPointDeletionResponse, error)
	// ListVerificationCandidates returns committed recovery points of a
	// Repository to verify, least recently verified first.
	ListVerificationCandidates(context.Context, *ListVerificationCandidatesRequest) (*ListVerificationCandidatesResponse, error)
	// SetVerification records a recovery point's verification result.
	SetVerification(context.Context, *SetVerificationRequest) (*SetVerificationResponse, error)
	// BeginPlatformBackup records a running Platform Protection run (ADR-0008)
	// and returns its ID and the System Repository (if one is designated).
	BeginPlatformBackup(context.Context, *BeginPlatformBackupRequest) (*BeginPlatformBackupResponse, error)
	// ExportPlatform streams the age-encrypted Platform Recovery Bundle
	// (tar -> zstd -> age to every escrow recipient) in ~1 MiB chunks. The
	// bundle is encrypted inside dbr2-server; plaintext never leaves it. The
	// last message carries the summary (plaintext manifest, no secrets).
	ExportPlatform(*ExportPlatformRequest, grpc.ServerStreamingServer[ExportPlatformResponse]) error
	// RecordPlatformBackup stores the outcome of a platform backup (audit
	// event, and an alert when it is partial or failed).
	RecordPlatformBackup(context.Context, *RecordPlatformBackupRequest) (*RecordPlatformBackupResponse, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) PrepareBackup(context.Context, *PrepareBackupRequest) (*PrepareBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareBackup not implemented")
}
func (UnimplementedPlatformServiceServer) EnsureAgentAccess(context.Context, *EnsureAgentAccessRequest) (*EnsureAgentAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureAgentAccess not implemented")
}
func (UnimplementedPlatformServiceServer) CompleteBackup(context.Context, *CompleteBackupRequest) (*CompleteBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteBackup not implemented")
}
func (UnimplementedPlatformServiceServer) GetRepository(context.Context, *GetRepositoryRequest) (*GetRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepository not implemented")
}
func (UnimplementedPlatformServiceServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedPlatformServiceServer) IndexRecoveryPoints(context.Context, *IndexRecoveryPointsRequest) (*IndexRecoveryPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexRecoveryPoints not implemented")
}
func (UnimplementedPlatformServiceServer) RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedPlatformServiceServer) PrepareRestore(context.Context, *PrepareRestoreRequest) (*PrepareRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareRestore not implemented")
}
func (UnimplementedPlatformServiceServer) GrantRestoreAccess(context.Context, *GrantRestoreAccessRequest) (*GrantRestoreAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantRestoreAccess not implemented")
}
func (UnimplementedPlatformServiceServer) RevokeRestoreAccess(context.Context, *RevokeRestoreAccessRequest) (*RevokeRestoreAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeRestoreAccess not implemented")
}
func (UnimplementedPlatformServiceServer) UpdateRestore(context.Context, *UpdateRestoreRequest) (*UpdateRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestore not implemented")
}
func (UnimplementedPlatformServiceServer) ListRetentionCandidates(context.Context, *ListRetentionCandidatesRequest) (*ListRetentionCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRetentionCandidates not implemented")
}
func (UnimplementedPlatformServiceServer) BeginRecoveryPointDeletion(context.Context, *BeginRecoveryPointDeletionRequest) (*BeginRecoveryPointDeletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginRecoveryPointDeletion not implemented")
}
func (UnimplementedPlatformServiceServer) FinishRecoveryPointDeletion(context.Context, *FinishRecoveryPointDeletionRequest) (*FinishRecoveryPointDeletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRecoveryPointDeletion not implemented")
}
func (UnimplementedPlatformServiceServer) ListVerificationCandidates(context.Context, *ListVerificationCandidatesRequest) (*ListVerificationCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVerificationCandidates not implemented")
}
func (UnimplementedPlatformServiceServer) SetVerification(context.Context, *SetVerificationRequest) (*SetVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVerification not implemented")
}
func (UnimplementedPlatformServiceServer) BeginPlatformBackup(context.Context, *BeginPlatformBackupRequest) (*BeginPlatformBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginPlatformBackup not implemented")
}
func (UnimplementedPlatformServiceServer) ExportPlatform(*ExportPlatformRequest, grpc.ServerStreamingServer[ExportPlatformResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExportPlatform not implemented")
}
func (UnimplementedPlatformServiceServer) RecordPlatformBackup(context.Context, *RecordPlatformBackupRequest) (*RecordPlatformBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordPlatformBackup not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue()                         {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_PrepareBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).PrepareBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_PrepareBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).PrepareBackup(ctx, req.(*PrepareBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_EnsureAgentAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureAgentAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).EnsureAgentAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_EnsureAgentAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).EnsureAgentAccess(ctx, req.(*EnsureAgentAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_CompleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CompleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CompleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CompleteBackup(ctx, req.(*CompleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetRepository(ctx, req.(*GetRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_IndexRecoveryPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRecoveryPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).IndexRecoveryPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_IndexRecoveryPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).IndexRecoveryPoints(ctx, req.(*IndexRecoveryPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).RecordEvent(ctx, req.(*RecordEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_PrepareRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).PrepareRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_PrepareRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).PrepareRestore(ctx, req.(*PrepareRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GrantRestoreAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRestoreAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GrantRestoreAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GrantRestoreAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GrantRestoreAccess(ctx, req.(*GrantRestoreAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_RevokeRestoreAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRestoreAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).RevokeRestoreAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_RevokeRestoreAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).RevokeRestoreAccess(ctx, req.(*RevokeRestoreAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_UpdateRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).UpdateRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_UpdateRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).UpdateRestore(ctx, req.(*UpdateRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListRetentionCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRetentionCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListRetentionCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListRetentionCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListRetentionCandidates(ctx, req.(*ListRetentionCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_BeginRecoveryPointDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRecoveryPointDeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).BeginRecoveryPointDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_BeginRecoveryPointDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).BeginRecoveryPointDeletion(ctx, req.(*BeginRecoveryPointDeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_FinishRecoveryPointDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRecoveryPointDeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).FinishRecoveryPointDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_FinishRecoveryPointDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).FinishRecoveryPointDeletion(ctx, req.(*FinishRecoveryPointDeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListVerificationCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVerificationCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListVerificationCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListVerificationCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListVerificationCandidates(ctx, req.(*ListVerificationCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_SetVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).SetVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_SetVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).SetVerification(ctx, req.(*SetVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_BeginPlatformBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginPlatformBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).BeginPlatformBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_BeginPlatformBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).BeginPlatformBackup(ctx, req.(*BeginPlatformBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ExportPlatform_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportPlatformRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformServiceServer).ExportPlatform(m, &grpc.GenericServerStream[ExportPlatformRequest, ExportPlatformResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformService_ExportPlatformServer = grpc.ServerStreamingServer[ExportPlatformResponse]

func _PlatformService_RecordPlatformBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPlatformBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).RecordPlatformBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_RecordPlatformBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).RecordPlatformBackup(ctx, req.(*RecordPlatformBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.v1.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareBackup",
			Handler:    _PlatformService_PrepareBackup_Handler,
		},
		{
			MethodName: "EnsureAgentAccess",
			Handler:    _PlatformService_EnsureAgentAccess_Handler,
		},
		{
			MethodName: "CompleteBackup",
			Handler:    _PlatformService_CompleteBackup_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _PlatformService_GetRepository_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _PlatformService_ListRepositories_Handler,
		},
		{
			MethodName: "IndexRecoveryPoints",
			Handler:    _PlatformService_IndexRecoveryPoints_Handler,
		},
		{
			MethodName: "RecordEvent",
			Handler:    _PlatformService_RecordEvent_Handler,
		},
		{
			MethodName: "PrepareRestore",
			Handler:    _PlatformService_PrepareRestore_Handler,
		},
		{
			MethodName: "GrantRestoreAccess",
			Handler:    _PlatformService_GrantRestoreAccess_Handler,
		},
		{
			MethodName: "RevokeRestoreAccess",
			Handler:    _PlatformService_RevokeRestoreAccess_Handler,
		},
		{
			MethodName: "UpdateRestore",
			Handler:    _PlatformService_UpdateRestore_Handler,
		},
		{
			MethodName: "ListRetentionCandidates",
			Handler:    _PlatformService_ListRetentionCandidates_Handler,
		},
		{
			MethodName: "BeginRecoveryPointDeletion",
			Handler:    _PlatformService_BeginRecoveryPointDeletion_Handler,
		},
		{
			MethodName: "FinishRecoveryPointDeletion",
			Handler:    _PlatformService_FinishRecoveryPointDeletion_Handler,
		},
		{
			MethodName: "ListVerificationCandidates",
			Handler:    _PlatformService_ListVerificationCandidates_Handler,
		},
		{
			MethodName: "SetVerification",
			Handler:    _PlatformService_SetVerification_Handler,
		},
		{
			MethodName: "BeginPlatformBackup",
			Handler:    _PlatformService_BeginPlatformBackup_Handler,
		},
		{
			MethodName: "RecordPlatformBackup",
			Handler:    _PlatformService_RecordPlatformBackup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportPlatform",
			Handler:       _PlatformService_ExportPlatform_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control/v1/control.proto",
}
