// SPDX-License-Identifier: Apache-2.0

// Internal control plane protocol between dbr2-worker (Temporal activities)
// and the Agent Gateway in dbr2-server (ADR-0001). Not exposed outside the
// deployment network; authenticated with the internal token.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: control/v1/control.proto

package controlv1

import (
	v1 "github.com/AxiomOperator/dbr2/internal/agentpb/agent/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DispatchRequest identifies the agent and the command.
type DispatchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command             *v1.Command            `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	WaitForAgentSeconds uint32                 `protobuf:"varint,3,opt,name=wait_for_agent_seconds,json=waitForAgentSeconds,proto3" json:"wait_for_agent_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DispatchRequest) GetCommand() *v1.Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *DispatchRequest) GetWaitForAgentSeconds() uint32 {
	if x != nil {
		return x.WaitForAgentSeconds
	}
	return 0
}

// DispatchResponse carries one command update.
type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *v1.CommandUpdate      `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetUpdate() *v1.CommandUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

var File_control_v1_control_proto protoreflect.FileDescriptor

const file_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18control/v1/control.proto\x12\n" +
	"control.v1\x1a\x14agent/v1/agent.proto\"\x8e\x01\n" +
	"\x0fDispatchRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12+\n" +
	"\acommand\x18\x02 \x01(\v2\x11.agent.v1.CommandR\acommand\x123\n" +
	"\x16wait_for_agent_seconds\x18\x03 \x01(\rR\x13waitForAgentSeconds\"C\n" +
	"\x10DispatchResponse\x12/\n" +
	"\x06update\x18\x01 \x01(\v2\x17.agent.v1.CommandUpdateR\x06update2`\n" +
	"\x15GatewayControlService\x12G\n" +
	"\bDispatch\x12\x1b.control.v1.DispatchRequest\x1a\x1c.control.v1.DispatchResponse0\x01BEZCgithub.com/AxiomOperator/dbr2/internal/agentpb/control/v1;controlv1b\x06proto3"

var (
	file_control_v1_control_proto_rawDescOnce sync.Once
	file_control_v1_control_proto_rawDescData []byte
)

func file_control_v1_control_proto_rawDescGZIP() []byte {
	file_control_v1_control_proto_rawDescOnce.Do(func() {
		file_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)))
	})
	return file_control_v1_control_proto_rawDescData
}

var file_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_control_v1_control_proto_goTypes = []any{
	(*DispatchRequest)(nil),  // 0: control.v1.DispatchRequest
	(*DispatchResponse)(nil), // 1: control.v1.DispatchResponse
	(*v1.Command)(nil),       // 2: agent.v1.Command
	(*v1.CommandUpdate)(nil), // 3: agent.v1.CommandUpdate
}
var file_control_v1_control_proto_depIdxs = []int32{
	2, // 0: control.v1.DispatchRequest.command:type_name -> agent.v1.Command
	3, // 1: control.v1.DispatchResponse.update:type_name -> agent.v1.CommandUpdate
	0, // 2: control.v1.GatewayControlService.Dispatch:input_type -> control.v1.DispatchRequest
	1, // 3: control.v1.GatewayControlService.Dispatch:output_type -> control.v1.DispatchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_control_v1_control_proto_init() }
func file_control_v1_control_proto_init() {
	if File_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v1_control_proto_goTypes,
		DependencyIndexes: file_control_v1_control_proto_depIdxs,
		MessageInfos:      file_control_v1_control_proto_msgTypes,
	}.Build()
	File_control_v1_control_proto = out.File
	file_control_v1_control_proto_goTypes = nil
	file_control_v1_control_proto_depIdxs = nil
}
