// SPDX-License-Identifier: Apache-2.0
//
// @hey-api/openapi-ts configuration: TypeScript types and Zod 4 schemas for
// the DBR² API, generated from ../api/openapi.yaml (the contract exported by
// dbr2-server) into src/lib/api/generated/. Run `npm run generate:api` (or
// `make web-generate`) after the contract changes and commit the output; the
// unit test src/lib/api/generated.test.ts fails while it is stale.
//
// The input is patched before generation (never the file itself):
//  - int64 / uint64 integers stay JavaScript numbers (byte counts and
//    counters are far below 2^53) instead of the default BigInt coercion;
//  - `format: uuid` is dropped: IDs are opaque to the console and the server
//    validates them (Zod's uuid check also rejects well-known non-random IDs);
//  - a nullable enum (`type: [string, "null"]` + `enum` without null, which
//    is how Huma describes a *string) also accepts null, as the server sends;
//  - a `$ref` property documented as "null when …" (a Go pointer to a struct,
//    e.g. ApplicationDetail.analysis, RepositoryDTO.live) is made nullable:
//    Huma does not mark those nullable in the exported document.
import { defineConfig } from "@hey-api/openapi-ts";

export const GENERATED_HEADER = [
  "// Code generated by @hey-api/openapi-ts from api/openapi.yaml. DO NOT EDIT.",
  "// Regenerate with `npm run generate:api` (in web/) or `make web-generate`.",
];

type Json = { [key: string]: unknown };

function isObject(v: unknown): v is Json {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Applies the patches described above to every schema object in place. */
export function patchSpec(node: unknown): void {
  if (Array.isArray(node)) {
    for (const item of node) patchSpec(item);
    return;
  }
  if (!isObject(node)) return;
  if (node.format === "int64" || node.format === "uint64" || node.format === "uuid") {
    delete node.format;
  }
  const type = node.type;
  if (Array.isArray(type) && type.includes("null") && Array.isArray(node.enum) && !node.enum.includes(null)) {
    node.enum = [...node.enum, null];
  }
  const properties = node.properties;
  if (isObject(properties)) {
    for (const [name, prop] of Object.entries(properties)) {
      if (isObject(prop) && typeof prop.$ref === "string" && /\bnull when\b/i.test(String(prop.description ?? ""))) {
        properties[name] = { description: prop.description, anyOf: [{ $ref: prop.$ref }, { type: "null" }] };
      }
    }
  }
  for (const value of Object.values(node)) patchSpec(value);
}

export default defineConfig({
  input: process.env.DBR2_OPENAPI_INPUT ?? "../api/openapi.yaml",
  output: {
    path: process.env.DBR2_OPENAPI_OUTPUT ?? "src/lib/api/generated",
    header: GENERATED_HEADER,
    postProcess: [],
  },
  parser: {
    patch: { input: (spec) => patchSpec(spec) },
  },
  plugins: [
    "@hey-api/typescript",
    {
      name: "zod",
      // Go's time.Time marshals RFC 3339 with a zone designator (Z or ±hh:mm).
      dates: { offset: true },
    },
  ],
});
